
networks:
  shared-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/16


x-scylla-base: &scylla-base
  image: az-scylla:latest
  depends_on:
    - scylla-seed


services:
  dataservices-0:
    networks:
      shared-network:
        ipv4_address: 172.31.0.10
    image: az-dataservices:latest
    environment:
      - SCYLLA_URI=172.31.0.2
    depends_on:
      scylla-seed:
        condition: service_healthy
      
  
  api-0:
    networks:
      shared-network:
        ipv4_address: 172.31.0.20
    image: az-api:latest
    environment:
      - DATASERVICES_URI=172.31.0.10:3114
    depends_on:
      - dataservices-0


  scylla-seed:
    networks:
      shared-network:
        ipv4_address: 172.31.0.2
      
    image: az-scylla:latest
    volumes:
      - type: bind
        source: ./database/data/scylla0/
        target: /var/lib/scylla
      - type: bind
        source: ./database/main.yaml
        target: /etc/scylla/scylla.yaml
    hostname: scylla-seed

  scylla-node1:
    <<: *scylla-base
    volumes:
      - type: bind
        source: ./database/data/scylla1/
        target: /var/lib/scylla
      - type: bind
        source: ./database/main.yaml
        target: /etc/scylla/scylla.yaml
    networks:
      shared-network:
          ipv4_address: 172.31.0.3

  scylla-node2:
    <<: *scylla-base
    volumes:
      - type: bind
        source: ./database/data/scylla2/
        target: /var/lib/scylla
      - type: bind
        source: ./database/main.yaml
        target: /etc/scylla/scylla.yaml
    networks:
      shared-network:
          ipv4_address: 172.31.0.4

  scylla-node3:
    <<: *scylla-base
    volumes:
      - type: bind
        source: ./database/data/scylla3/
        target: /var/lib/scylla
      - type: bind
        source: ./database/main.yaml
        target: /etc/scylla/scylla.yaml
    networks:
      shared-network:
          ipv4_address: 172.31.0.5

  scylla-node4:
    <<: *scylla-base
    volumes:
      - type: bind
        source: ./database/data/scylla4/
        target: /var/lib/scylla
      - type: bind
        source: ./database/main.yaml
        target: /etc/scylla/scylla.yaml
    networks:
      shared-network:
          ipv4_address: 172.31.0.6