
networks:
  shared-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/16


x-scylla-base: &scylla-base
  image: az-scylla:latest
  depends_on:
    - scylla-seed


services:
  dataservices-0:
    networks:
      shared-network:
        ipv4_address: 172.31.0.10
    image: az-dataservices:latest
    environment:
      - SCYLLA_URI=172.31.0.2
    depends_on:
      scylla-seed:
        condition: service_healthy

  gateway-0:
    networks:
      shared-network:
        ipv4_address: 172.31.0.30
    image: az-gateway:latest
    environment:
      - DATASERVICES_URI=172.31.0.10:3114
      - DEPLOYMENT_MODE=prod
    depends_on:
      - dataservices-0
    ports:
      - 8081:8081
  
  api-0:
    networks:
      shared-network:
        ipv4_address: 172.31.0.20
    image: az-api:latest
    environment:
      - DATASERVICES_URI=172.31.0.10:3114
      - DEPLOYMENT_MODE=prod
    ports:
      - "80:80"
    volumes:
      - ./certs/cert.pem:/az7/api/certs/cert.pem:ro
      - ./certs/key.pem:/az7/api/certs/key.pem:ro


  scylla-seed:
    networks:
      shared-network:
        ipv4_address: 172.31.0.2
      
    image: az-scylla:latest
    volumes:
      - type: bind
        source: /db/scylla0/
        target: /var/lib/scylla
      - type: bind
        source: ./database/main.yaml
        target: /etc/scylla/scylla.yaml
    hostname: scylla-seed

  scylla-node1:
    <<: *scylla-base
    volumes:
      - type: bind
        source: /db/scylla1/
        target: /var/lib/scylla
      - type: bind
        source: ./database/main.yaml
        target: /etc/scylla/scylla.yaml
    networks:
      shared-network:
          ipv4_address: 172.31.0.3