
networks:
  shared-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/16


x-scylla-base: &scylla-base
  image: europe-west2-docker.pkg.dev/fyp-25coc251/az7-backend/database:latest
  depends_on:
    - scylla-seed
  stop_grace_period: 120s


services:
  jaeger:
    networks:
      shared-network:
        ipv4_address: 172.31.0.254
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 8080:16686
      - 4317:4317

  discoverystore-0:
    networks:
      - shared-network
    image: europe-west2-docker.pkg.dev/fyp-25coc251/az7-backend/discoverystore:latest


  dataservices:
    networks:
      - shared-network
    image: europe-west2-docker.pkg.dev/fyp-25coc251/az7-backend/dataservices:latest
    environment:
      SCYLLA_URI: 172.31.0.199
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://172.31.0.254:4317
      VALKEY_URI: redis://discoverystore-0:6379
    depends_on:
      scylla-seed:
        condition: service_healthy
      discoverystore-0:
        condition: service_healthy

  gateway-0:
    networks:
      - shared-network
    image: europe-west2-docker.pkg.dev/fyp-25coc251/az7-backend/gateway:latest
    environment:
        DEPLOYMENT_MODE: prod
        OTEL_URI: "http://jaeger:4317"
        VALKEY_URI: discoverystore-0:6379

    depends_on:
      discoverystore-0:
        condition: service_healthy
      dataservices:
        condition: service_started
    ports:
      - 8081:8081
  
  api-0:
    networks:
      - shared-network
    image: europe-west2-docker.pkg.dev/fyp-25coc251/az7-backend/api:latest
    environment:
      DEPLOYMENT_MODE: prod
      OTEL_URI: "http://jaeger:4317"
      API_SESSION_SIGNING_KEY: ${SECRET_KEY_API_SESSION_SIGN}
      API_SESSION_ENCRYPTION_KEY: ${SECRET_KEY_API_SESSION_ENCRYPT}
      VALKEY_URI: discoverystore-0:6379
      MEDIASERVICES_URI: https://mediaservices-7yrjjcng3q-nw.a.run.app:3119

      S3_PUBLIC_BUCKET: az7-public
      S3_PRIVATE_BUCKET: az7-private
      S3_ENDPOINT_URL: https://f2254f3b9e16dcc38a23d6ffc5db10a8.r2.cloudflarestorage.com
      S3_ACCESS_KEY_ID: ${SECRET_S3_ACCESS_KEY_ID}
      S3_ACCESS_KEY_SECRET: ${SECRET_S3_ACCESS_KEY_SECRET}
    ports:
      - "80:80"
    depends_on:
      discoverystore-0:
        condition: service_healthy
      dataservices:
        condition: service_started


  scylla-seed:
    networks:
      shared-network:
        ipv4_address: 172.31.0.199
      
    image: europe-west2-docker.pkg.dev/fyp-25coc251/az7-backend/database:latest
    volumes:
      - type: bind
        source: /db/scylla0/
        target: /var/lib/scylla
      - type: bind
        source: ./database/main.yaml
        target: /etc/scylla/scylla.yaml
    hostname: scylla-seed

  scylla-node1:
    <<: *scylla-base
    volumes:
      - type: bind
        source: /db/scylla1/
        target: /var/lib/scylla
      - type: bind
        source: ./database/main.yaml
        target: /etc/scylla/scylla.yaml
    networks:
      shared-network:
          ipv4_address: 172.31.0.200