
networks:
  shared-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/16


x-scylla-base: &scylla-base
  image: europe-west2-docker.pkg.dev/fyp-25coc251/az7-backend/database:latest
  depends_on:
    - scylla-seed
  stop_grace_period: 120s


services:
  jaeger:
    networks:
      shared-network:
        ipv4_address: 172.31.0.254
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 8080:16686

  dataservices-0:
    networks:
      shared-network:
        ipv4_address: 172.31.0.10
    image: europe-west2-docker.pkg.dev/fyp-25coc251/az7-backend/dataservices:latest
    environment:
      - SCYLLA_URI=172.31.0.2
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://172.31.0.254:4317
    depends_on:
      scylla-seed:
        condition: service_healthy

  gateway-0:
    networks:
      shared-network:
        ipv4_address: 172.31.0.30
    image: europe-west2-docker.pkg.dev/fyp-25coc251/az7-backend/gateway:latest
    environment:
        DEPLOYMENT_MODE: prod
        DATASERVICES_URI: "dataservices-0:3114"
        OTEL_URI: "http://jaeger:4317"
    depends_on:
      - dataservices-0
    ports:
      - 8081:8081
  
  api-0:
    networks:
      shared-network:
        ipv4_address: 172.31.0.20
    image: europe-west2-docker.pkg.dev/fyp-25coc251/az7-backend/api:latest
    environment:
        DEPLOYMENT_MODE: prod
        DATASERVICES_URI: "dataservices-0:3114"
        OTEL_URI: "http://jaeger:4317"
        API_SESSION_SIGNING_KEY: ${SECRET_KEY_API_SESSION_SIGN}
        API_SESSION_ENCRYPTION_KEY: ${SECRET_KEY_API_SESSION_ENCRYPT}
    ports:
      - "80:80"
    volumes:
      - ./certs/cert.pem:/az7/api/certs/cert.pem:ro
      - ./certs/key.pem:/az7/api/certs/key.pem:ro


  scylla-seed:
    networks:
      shared-network:
        ipv4_address: 172.31.0.2
      
    image: europe-west2-docker.pkg.dev/fyp-25coc251/az7-backend/database:latest
    volumes:
      - type: bind
        source: /db/scylla0/
        target: /var/lib/scylla
      - type: bind
        source: ./database/main.yaml
        target: /etc/scylla/scylla.yaml
    hostname: scylla-seed

  scylla-node1:
    <<: *scylla-base
    volumes:
      - type: bind
        source: /db/scylla1/
        target: /var/lib/scylla
      - type: bind
        source: ./database/main.yaml
        target: /etc/scylla/scylla.yaml
    networks:
      shared-network:
          ipv4_address: 172.31.0.3