
networks:
  shared-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/16


x-scylla-base: &scylla-base
  image: europe-west2-docker.pkg.dev/fyp-25coc251/az7-backend/database:latest
  depends_on:
    - scylla-seed
  stop_grace_period: 60s
  environment:
    SEED: "scylla-seed"


services:

  elasticsearch:
    networks:
      - shared-network
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f http://127.0.0.1:9200/_cluster/health?wait_for_status=yellow&timeout=5s || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 12
      start_period: 40s
    volumes:
      - type: bind
        source: ./elasticsearch/data/
        target: /var/lib/elasticsearch

  jaeger:
    networks:
      - shared-network
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 16686:16686
    
  
  discoverystore-0:
    networks:
      - shared-network
    image: europe-west2-docker.pkg.dev/fyp-25coc251/az7-backend/discoverystore:latest
  
  gc-0:
    networks:
      - shared-network
    image: europe-west2-docker.pkg.dev/fyp-25coc251/az7-backend/garbagecollector:latest
    environment:
      BUCKETS: 0-0
      OTEL_URI: "http://jaeger:4317"
      VALKEY_URI: discoverystore-0:6379

      S3_PUBLIC_BUCKET: az7-dev-public
      S3_PRIVATE_BUCKET: az7-dev-private
      S3_ENDPOINT_URL: https://f2254f3b9e16dcc38a23d6ffc5db10a8.r2.cloudflarestorage.com
      S3_ACCESS_KEY_ID: ${SECRET_S3_ACCESS_KEY_ID}
      S3_ACCESS_KEY_SECRET: ${SECRET_S3_ACCESS_KEY_SECRET}
    depends_on:
      dataservices:
        condition: service_started
      discoverystore-0:
        condition: service_healthy

  watchdog:
    networks:
      - shared-network
    image: europe-west2-docker.pkg.dev/fyp-25coc251/az7-backend/watchdog:latest
    environment:
      OTEL_URI: "http://jaeger:4317"
      VALKEY_URI: discoverystore-0:6379

    depends_on:
      discoverystore-0:
        condition: service_healthy

  amplifier:
    deploy:
      mode: replicated
      replicas: ${AMPLIFIER_REPLICAS:-1}

    networks:
      - shared-network
    image: europe-west2-docker.pkg.dev/fyp-25coc251/az7-backend/amplifier:latest
    environment:
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://jaeger:4317
      VALKEY_URI: redis://discoverystore-0:6379

    depends_on:
      discoverystore-0:
        condition: service_healthy

  dataservices:
    deploy:
      mode: replicated
      replicas: ${DATASERVICES_REPLICAS:-1}

    networks:
      - shared-network
    image: europe-west2-docker.pkg.dev/fyp-25coc251/az7-backend/dataservices:latest
    environment:
      SCYLLA_URI: 172.31.0.199
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://jaeger:4317
      VALKEY_URI: redis://discoverystore-0:6379
      ELASTICSEARCH_URI: http://elasticsearch:9200

    depends_on:
      scylla-seed:
        condition: service_healthy
      discoverystore-0:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      
  mediaservices-0:
    networks:
      - shared-network
    image: europe-west2-docker.pkg.dev/fyp-25coc251/az7-backend/mediaservices:latest
    environment:
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://jaeger:4317

      # dev bucket endpoint
      S3_PUBLIC_BUCKET: az7-dev-public
      S3_PRIVATE_BUCKET: az7-dev-private
      S3_ENDPOINT_URL: https://f2254f3b9e16dcc38a23d6ffc5db10a8.r2.cloudflarestorage.com
      S3_ACCESS_KEY_ID: ${SECRET_S3_ACCESS_KEY_ID}
      S3_ACCESS_KEY_SECRET: ${SECRET_S3_ACCESS_KEY_SECRET}

  api:
    deploy:
      mode: replicated
      replicas: ${API_REPLICAS:-1}
    networks:
      - shared-network
    image: europe-west2-docker.pkg.dev/fyp-25coc251/az7-backend/api:latest
    environment:
      OTEL_URI: "http://jaeger:4317"
      API_SESSION_SIGNING_KEY: ${SECRET_KEY_API_SESSION_SIGN}
      API_SESSION_ENCRYPTION_KEY: ${SECRET_KEY_API_SESSION_ENCRYPT}
      VALKEY_URI: discoverystore-0:6379
      MEDIASERVICES_URI: mediaservices-0:3119

      S3_PUBLIC_BUCKET: az7-dev-public
      S3_PRIVATE_BUCKET: az7-dev-private
      S3_ENDPOINT_URL: https://f2254f3b9e16dcc38a23d6ffc5db10a8.r2.cloudflarestorage.com
      S3_ACCESS_KEY_ID: ${SECRET_S3_ACCESS_KEY_ID}
      S3_ACCESS_KEY_SECRET: ${SECRET_S3_ACCESS_KEY_SECRET}

      ELASTICSEARCH_URI: http://elasticsearch:9200

    depends_on:
      discoverystore-0:
        condition: service_healthy
      dataservices:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    ports:
      - 8000:8000
  
  gateway:
    deploy:
      mode: replicated
      replicas: ${GATEWAY_REPLICAS:-1}
    networks:
      - shared-network
    image: europe-west2-docker.pkg.dev/fyp-25coc251/az7-backend/gateway:latest
    environment:
        OTEL_URI: "http://jaeger:4317"
        VALKEY_URI: discoverystore-0:6379

    depends_on:
      discoverystore-0:
        condition: service_healthy
      dataservices:
        condition: service_started


  scylla-seed:
    networks:
      shared-network:
        ipv4_address: 172.31.0.199
      
    image: europe-west2-docker.pkg.dev/fyp-25coc251/az7-backend/database:latest
    volumes:
      - type: bind
        source: /db/conf/main.yaml
        target: /etc/scylla/scylla.yaml
      - type: bind
        source: /db/data
        target: /var/lib/scylla
      - type: bind
        source: /etc/scylla.d/io.conf
        target: /etc/scylla.d/io.conf
    environment:
      SEED: 172.31.0.199
      SMP:  12
      MEM:  24G
      SCYLLA_ARGS:  --overprovisioned 1 --developer-mode 0
    ulimits:
      nproc: 65535
      nofile:
        soft: 1000000
        hard: 1000000
    privileged: true
    network_mode: "host"
    hostname: scylla-seed
    environment:
      SEED: "172.31.0.199"
