from typing import Final
__all__ = (
    "USERNAME_MAX_LENGTH",
    "USERNAME_MIN_LENGTH",
    "DEVICE_NAME_MAX_LENGTH",
    "DEVICE_NAME_MIN_LENGTH",
    "CHANNEL_NAME_MIN_LENGTH",
    "CHANNEL_NAME_MAX_LENGTH",
    "CHANNEL_MAX_NUM_MEMBERS",
)

USERNAME_MAX_LENGTH: Final[int] = 24
USERNAME_MIN_LENGTH: Final[int] = 2

DEVICE_NAME_MAX_LENGTH: Final[int] = 32
DEVICE_NAME_MIN_LENGTH: Final[int] = 1

CHANNEL_NAME_MAX_LENGTH: Final[int] = 48
CHANNEL_NAME_MIN_LENGTH: Final[int] = 1

CHANNEL_MAX_NUM_MEMBERS: Final[int] = 15

USER_MAX_NUM_DEVICES: Final[int] = 15