from itertools import chain
import json



cql_statements: list[list[str]] = []

conf: dict[str, dict[str, str | bool | int]] = {}
with open("./database/model_conf.json") as f:
    conf |= json.load(f)


with open("./database/database.cql", "r") as f:
    table_definitions = f.read()
    for statement in table_definitions.split(";"):
        lines = map(lambda l: l.split("--")[0].strip(), statement.split("\n"))
        if lines := list(filter(lambda l: l, lines)):
            cql_statements.append(lines)
    

tables: dict[str, Table] = {}


class Row:
    def __init__(self, definition: str):
        parts = definition.split()
        key, datatype, *_ = parts

        if datatype[-1] == ",":
            datatype = datatype[:-1]

        self.key: str = key
        self.optional: bool = key.startswith("opt_")
        self.datatype: str = datatype

    def __repr__(self):
        return f"<Row {self.key}: {self.datatype}>"

class Table:
    def __init__(self, name: str, rows: list[str], pk: str | None, lwt: bool = False):
        self.fqn: str = name
        self.name: str = name.split(".")[1]
        self.keyspace: str = name.split(".")[0]
        self.rows: list[Row] = []
        self.pk = pk
        self.rows = [Row(row) for row in rows]
        self.lwt: bool = lwt

    def __repr__(self):
        return f"<Table {self.name} {self.pk} with {self.rows}>"


for statement in cql_statements:
    if not statement[0].startswith("CREATE TABLE"):
        continue
    
    iterator = iter(statement)

    name = next(iterator).split()[2]
    table_conf = conf.get(name, {})
    rows: list[str] = []
    pk: str | None = None
    while row := next(iterator): # stopiteration: table without primary key
        if row.startswith("PRIMARY KEY"):
            pk = row
            break
        rows.append(row)
    
    lwt = table_conf.get("lwt", False)
    assert isinstance(lwt, bool)
    t = Table(name, rows, pk, lwt)
    tables[name] = t



class ModelGenerator:
    def __init__(self, table: Table):
        self.table = table
        self.language: str
    
    @property
    def keyspace(self) -> str:
        return self.table.name.split(".")[0]
    

    def generate(self) -> str: ...


class RustModelGenerator(ModelGenerator):
    # https://rust-driver.docs.scylladb.com/stable/data-types/data-types.html
    DATATYPE_MAP = {
        "boolean": "bool",
        "tinyint": "i8",
        "smallint": "i16",
        "int": "i32",
        "bigint": "i64",
        "float": "f32",
        "double": "f64",
        "text": "String",
        "blob": "Vec<u8>",
        "varchar": "String",
        "timeuuid": "value::CqlTimeuuid",
        "uuid": "uuid::Uuid",
        "timestamp": "value::CqlTimestamp",
        "set<timeuuid>": "HashSet<value::CqlTimeuuid>",
        "counter": "value::Counter",
    }

    @classmethod
    def map_datatype(cls, row: Row) -> str:
        t = cls.DATATYPE_MAP[row.datatype.lower()]
        if row.optional:
            return f"Option<{t}>"
        return t

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.dependencies: set[str] = set()

    def generate_struct(self, struct_name: str, lwt: bool = False) -> list[str]:
        lines = []
        
        lines.append("#[derive(Debug, DeserializeRow, Clone)]")
        lines.append(f"pub struct {struct_name} {{")

        rows = self.table.rows


        if lwt:
            lines.append(f'    #[scylla(rename = "[applied]")]')
            lines.append(f"    pub applied: bool,")
            rows = list(self.table.rows)
            for row in rows:
                row.optional = True


        for row in rows:
            rust_type = self.map_datatype(row)
            lines.append(f"    pub {row.key}: {rust_type},")

            # dependency tracking
            if "value::" in rust_type:
                self.dependencies.add("use scylla::value;")

            if "uuid::" in rust_type:
                self.dependencies.add("use uuid;")

            if "HashSet" in rust_type:
                self.dependencies.add("use std::collections::HashSet;")
        lines.append("}")
        return lines

    def generate(self) -> str:
        header = [
            "// Generated by model_generator.py",
            "#![allow(nonstandard_style)]",
        ]
        lines: list[str] = []
        self.dependencies.add("use scylla::DeserializeRow;")
        struct_name = "".join(word.capitalize() for word in self.table.name.split("_"))

        lines.extend(self.generate_struct(struct_name, False))

        if self.table.lwt:
            lines.extend(self.generate_struct(f"LWT{struct_name}", True))

        

        return "\n".join(chain(header, sorted(self.dependencies), lines))



for table in tables.values():
    path = table.name
    print(f"Generating model for table {table.fqn}")
    try:
        rust_code = RustModelGenerator(table).generate()
    except Exception:
        print(f"Error generating table: {table}")
        raise
    with open(f"./dataservices/src/models/{path}.rs", "w+") as f:
        f.write(rust_code)

with open("./dataservices/src/models/mod.rs", "w+") as f:
    mod_lines = [f"pub mod {table.name};" for table in tables.values()]
    f.write("\n".join(mod_lines))


    