from itertools import chain



cql_statements: list[list[str]] = []

with open("../database/database.cql", "r") as f:
    table_definitions = f.read()
    for statement in table_definitions.split(";"):
        lines = map(lambda l: l.split("--")[0].strip(), statement.split("\n"))
        if lines := list(filter(lambda l: l, lines)):
            cql_statements.append(lines)
    

tables: dict[str, Table] = {}


class Row:
    def __init__(self, definition: str):
        parts = definition.split()
        key, datatype, *_ = parts

        if datatype[-1] == ",":
            datatype = datatype[:-1]

        self.key = key
        self.datatype = datatype

    def __repr__(self):
        return f"<Row {self.key}: {self.datatype}>"

class Table:
    def __init__(self, name: str, rows: list[str], pk: str | None):
        self.fqn: str = name
        self.name: str = name.split(".")[1]
        self.keyspace: str = name.split(".")[0]
        self.rows: list[Row] = []
        self.pk = pk
        self.rows = [Row(row) for row in rows]

    def __repr__(self):
        return f"<Table {self.name} {self.pk} with {self.rows}>"


for statement in cql_statements:
    if not statement[0].startswith("CREATE TABLE"):
        continue
    
    iterator = iter(statement)

    name = next(iterator).split()[2]
    rows: list[str] = []
    pk: str | None = None
    while row := next(iterator):
        if row.startswith("PRIMARY KEY"):
            pk = row
            break
        rows.append(row)
    t = Table(name, rows, pk)
    tables[name] = t



class ModelGenerator:
    def __init__(self, table: Table):
        self.table = table
        self.language: str
    
    @property
    def keyspace(self) -> str:
        return self.table.name.split(".")[0]
    

    def generate(self) -> str: ...


class RustModelGenerator(ModelGenerator):
    # https://rust-driver.docs.scylladb.com/stable/data-types/data-types.html
    DATATYPE_MAP = {
        "boolean": "bool",
        "tinyint": "i8",
        "smallint": "i16",
        "int": "i32",
        "bigint": "i64",
        "float": "f32",
        "double": "f64",
        "text": "String",
        "blob": "Vec<u8>",
        "varchar": "String",
        "timeuuid": "value::CqlTimeuuid",
        "uuid": "uuid::Uuid",
        "timestamp": "value::CqlTimestamp",
    }

    @classmethod
    def map_datatype(cls, datatype: str) -> str:
        return cls.DATATYPE_MAP[datatype.lower()]

    def generate(self) -> str:
        header = [
            "// Generated by model_generator.py",
            "#![allow(nonstandard_style)]",
        ]
        lines: list[str] = []
        dependencies: set[str] = set()
        dependencies.add("use scylla::DeserializeRow;")

        struct_name = "".join(word.capitalize() for word in self.table.name.split("_"))
        lines.append("#[derive(Debug, DeserializeRow)]")
        lines.append(f"pub struct {struct_name} {{")
        for row in self.table.rows:
            rust_type = self.map_datatype(row.datatype)
            lines.append(f"    pub {row.key}: {rust_type},")

            # dependency tracking
            if rust_type.startswith("value::"):
                dependencies.add("use scylla::value;")
            if rust_type.startswith("uuid::"):
                dependencies.add("use uuid;")
        lines.append("}")

        return "\n".join(chain(header, dependencies, lines))



for table in tables.values():
    path = table.name
    print(f"Generating model for table {table.fqn}")
    try:
        rust_code = RustModelGenerator(table).generate()
    except Exception:
        print(f"Error generating table: {table}")
        raise
    with open(f"./src/models/{path}.rs", "w+") as f:
        f.write(rust_code)

with open("./src/models/mod.rs", "w+") as f:
    mod_lines = [f"pub mod {table.name};" for table in tables.values()]
    f.write("\n".join(mod_lines))


    