syntax = "proto3";

package amplifier.amplify;

import "plib.proto";

service AmplifierService {
    rpc FanOut (FanOutRequest) returns (FanOutResponse);
}

message FanOutRequest {
    oneof request_type {
        FanOutMessage single = 1;
        FanOutPerUserMessages many = 2;
    }
}


message Recipient {
    plib.pUUID user_id = 1;
    string host = 2;
}

message LocalRecipients {
    string host = 1;
    repeated plib.pUUID recipients = 2;
}

message FanOutMessage {
    repeated LocalRecipients recipients = 1;
    bytes payload = 2;
}

message FanOutPerUserMessages {
    repeated PerUserMessage messages = 1;
}

message PerUserMessage {
    Recipient to = 1;
    bytes message = 2;
}


message FanOutResponse {}