syntax = "proto3";

package intraservice.internalmesssage;


import "traceparent.proto";
import "plib.proto";



message IntraMessage {
    plib.pUUID to = 1;
    optional traceparent.TraceParent traceparent = 2;
    oneof event {
        EventSessionCreate session_create = 3;
        EventChannelCreate channel_create = 4;
        EventFriendshipUpdate friendship_update = 5;
    }
}

message EventSessionCreate {
    uint32 ipaddress = 1;
}

message EventChannelCreate {
    plib.pUUID channel_id = 1;
    optional bytes encrypted_channel_name = 2;
    bytes encrypted_channel_key = 3;
}

message EventFriendshipUpdate {
    plib.pUUID peer_id = 1;
    optional uint32 relationship_type = 2;
}
