syntax = "proto3";

package intraservice.internalmesssage;


import "traceparent.proto";
import "plib.proto";



message IntraMessage {
    plib.pUUID to = 1;
    optional traceparent.TraceParent traceparent = 2;
    oneof event {
        EventSessionCreate session_create = 3;
        EventChannelCreate channel_create = 4;
        EventFriendshipUpdate friendship_update = 5;
        EventMessageCreate message_create = 6;
        EventUserTyping user_typing = 7;
    }
}

message EventSessionCreate {
    uint32 ipaddress = 1;
}

message EventChannelCreate {
    plib.pUUID channel_id = 1;
    optional bytes encrypted_channel_name = 2;
    bytes encrypted_channel_key = 3;
}

message EventFriendshipUpdate {
    plib.pUUID peer_id = 1;
    optional uint32 relationship_type = 2;
}

message EventMessageCreate {
    plib.pUUID author_id = 1;
    plib.pUUID message_id = 5;
    plib.pUUID channel_id = 4;
    optional bytes content = 2;
    int32 message_type = 3;
    optional plib.pUUID attachment_id = 6;
}

message EventUserTyping {
    plib.pUUID author_id = 1;
    plib.pUUID channel_id = 2;
}