syntax = "proto3";

package mediaservices.transformer;

import "asset.proto";

service TransformerService {
    rpc TransformImage (TransformImageRequest) returns (TransformImageResponse);
    rpc TransformVideo (stream TransformVideoRequest) returns (TransformVideoResponse);
}




message TransformImageRequest {
    mediaservices.asset.Asset asset = 1;
    bytes data = 2;
}

message TransformImageResponse {
    
}

message TransformVideoRequest {
    oneof next {
        mediaservices.asset.Asset asset = 1;
        bytes chunk = 2;
    }
}

message TransformVideoResponse {
    
}