// Generated by model_generator.py
#![allow(nonstandard_style)]
use scylla::value;
use uuid;
pub struct Asset {
    pub asset_id: value::CqlTimeuuid,
    pub bucket_id: uuid::Uuid,
    pub asset_type: i32,
    pub content_type: String,
    pub file_name: String,
}