// Generated by model_generator.py
#![allow(nonstandard_style)]
use scylla::value;
use scylla::DeserializeRow;
#[derive(Debug, DeserializeRow)]
pub struct BlockedUser {
    pub blocker__user_id: value::CqlTimeuuid,
    pub blocked__user_id: value::CqlTimeuuid,
}