// Generated by model_generator.py
#![allow(nonstandard_style)]
use crate::protos::plib::AllignedCqlTimeuuid;
use scylla::DeserializeRow;
use std::collections::HashSet;
#[derive(Debug, DeserializeRow, Clone)]
pub struct Channel {
    pub channel_id: AllignedCqlTimeuuid,
    pub channel_type: i32,
    pub latest_bucket: i64,
    pub opt_channel_name: Option<Vec<u8>>,
    pub channel_members: HashSet<AllignedCqlTimeuuid>,
    pub opt_channel_icon_asset_id: Option<AllignedCqlTimeuuid>,
}