// Generated by model_generator.py
#![allow(nonstandard_style)]
use scylla::DeserializeRow;
use scylla::value;
#[derive(Debug, DeserializeRow)]
pub struct ChannelCounter {
    pub channel_id: value::CqlTimeuuid,
    pub message_ctr: value::Counter,
}