// Generated by model_generator.py
#![allow(nonstandard_style)]
use crate::protos::plib::AllignedCqlTimeuuid;
use scylla::DeserializeRow;
use scylla::value;
#[derive(Debug, DeserializeRow, Clone)]
pub struct ChannelCounter {
    pub channel_id: AllignedCqlTimeuuid,
    pub message_ctr: value::Counter,
}