// Generated by model_generator.py
#![allow(nonstandard_style)]
use scylla::DeserializeRow;
use scylla::value;
use std::collections::HashSet;
#[derive(Debug, DeserializeRow)]
pub struct Channel {
    pub channel_id: value::CqlTimeuuid,
    pub channel_type: i32,
    pub opt_channel_name: Option<String>,
    pub channel_members: HashSet<value::CqlTimeuuid>,
    pub opt_channel_icon_asset_id: Option<uuid::Uuid>,
}