// Generated by model_generator.py
#![allow(nonstandard_style)]
use scylla::value;
pub struct Friendship {
    pub lower__user_id: value::CqlTimeuuid,
    pub higher__user_id: value::CqlTimeuuid,
    pub created_at: value::CqlTimestamp,
}