// Generated by model_generator.py
#![allow(nonstandard_style)]
use scylla::DeserializeRow;
use scylla::value;
#[derive(Debug, DeserializeRow)]
pub struct Friendship {
    pub lower__user_id: value::CqlTimeuuid,
    pub higher__user_id: value::CqlTimeuuid,
    pub created_at: value::CqlTimestamp,
}
impl Friendship {
    pub fn consume(self) -> (
        value::CqlTimeuuid,
        value::CqlTimeuuid,
        value::CqlTimestamp,
    ) {
        (
            self.lower__user_id,
            self.higher__user_id,
            self.created_at,
        )
    }
}