// Generated by model_generator.py
#![allow(nonstandard_style)]
use scylla::value;
pub struct FriendshipRequest {
    pub requester__user_id: value::CqlTimeuuid,
    pub recipient__user_id: value::CqlTimeuuid,
}