// Generated by model_generator.py
#![allow(nonstandard_style)]
use scylla::DeserializeRow;
use scylla::value;
#[derive(Debug, DeserializeRow)]
pub struct FriendshipRequest {
    pub requester__user_id: value::CqlTimeuuid,
    pub recipient__user_id: value::CqlTimeuuid,
}