// Generated by model_generator.py
#![allow(nonstandard_style)]
use scylla::DeserializeRow;
use scylla::value;
#[derive(Debug, DeserializeRow)]
pub struct MessageAttachment {
    pub message_id: value::CqlTimeuuid,
    pub asset_id: value::CqlTimeuuid,
}