// Generated by model_generator.py
#![allow(nonstandard_style)]
use scylla::DeserializeRow;
use uuid;
use scylla::value;
#[derive(Debug, DeserializeRow)]
pub struct MessageChannelMember {
    pub channel_id: uuid::Uuid,
    pub member__user_id: value::CqlTimeuuid,
    pub joined_at: value::CqlTimestamp,
    pub encrypyed_shared_key: Vec<u8>,
}
impl MessageChannelMember {
    pub fn consume(self) -> (
        uuid::Uuid,
        value::CqlTimeuuid,
        value::CqlTimestamp,
        Vec<u8>,
    ) {
        (
            self.channel_id,
            self.member__user_id,
            self.joined_at,
            self.encrypyed_shared_key,
        )
    }
}