// Generated by model_generator.py
#![allow(nonstandard_style)]
use uuid;
use scylla::value;
use scylla::DeserializeRow;
#[derive(Debug, DeserializeRow)]
pub struct MessageChannel {
    pub channel_id: uuid::Uuid,
    pub name: String,
    pub channel_type: i32,
    pub owner__user_id: value::CqlTimeuuid,
}