// Generated by model_generator.py
#![allow(nonstandard_style)]
use scylla::DeserializeRow;
use uuid;
use scylla::value;
#[derive(Debug, DeserializeRow)]
pub struct MessageChannel {
    pub channel_id: uuid::Uuid,
    pub name: String,
    pub channel_type: i32,
    pub owner__user_id: value::CqlTimeuuid,
}
impl MessageChannel {
    pub fn consume(self) -> (
        uuid::Uuid,
        String,
        i32,
        value::CqlTimeuuid,
    ) {
        (
            self.channel_id,
            self.name,
            self.channel_type,
            self.owner__user_id,
        )
    }
}