// Generated by model_generator.py
#![allow(nonstandard_style)]
use scylla::DeserializeRow;
use uuid;
use scylla::value;
#[derive(Debug, DeserializeRow)]
pub struct MessageAttachment {
    pub message_id: value::CqlTimeuuid,
    pub asset_id: uuid::Uuid,
}
impl MessageAttachment {
    pub fn consume(self) -> (
        value::CqlTimeuuid,
        uuid::Uuid,
    ) {
        (
            self.message_id,
            self.asset_id,
        )
    }
}