// Generated by model_generator.py
#![allow(nonstandard_style)]
use scylla::DeserializeRow;
use uuid;
use scylla::value;
#[derive(Debug, DeserializeRow)]
pub struct Message {
    pub channel_id: uuid::Uuid,
    pub bucket: i64,
    pub message_id: value::CqlTimeuuid,
    pub message_type: i32,
    pub opt_last_edited: Option<value::CqlTimestamp>,
    pub opt_content: Option<String>,
}
impl Message {
    pub fn consume(self) -> (
        uuid::Uuid,
        i64,
        value::CqlTimeuuid,
        i32,
        Option<value::CqlTimestamp>,
        Option<String>,
    ) {
        (
            self.channel_id,
            self.bucket,
            self.message_id,
            self.message_type,
            self.opt_last_edited,
            self.opt_content,
        )
    }
}