// Generated by model_generator.py
#![allow(nonstandard_style)]
use crate::protos::plib::AllignedCqlTimeuuid;
use scylla::DeserializeRow;
use scylla::value;
#[derive(Debug, DeserializeRow, Clone)]
pub struct Message {
    pub channel_id: AllignedCqlTimeuuid,
    pub bucket: i64,
    pub message_id: AllignedCqlTimeuuid,
    pub author_id: AllignedCqlTimeuuid,
    pub message_type: i32,
    pub opt_last_edited: Option<value::CqlTimestamp>,
    pub opt_content: Option<Vec<u8>>,
    pub opt_additional_content: Option<Vec<u8>>,
    pub opt_attachment_asset_id: Option<AllignedCqlTimeuuid>,
    pub opt_in_reply_to: Option<AllignedCqlTimeuuid>,
}