// Generated by model_generator.py
#![allow(nonstandard_style)]
use scylla::value;
use uuid;
pub struct MessageChannelMember {
    pub channel_id: uuid::Uuid,
    pub member__user_id: value::CqlTimeuuid,
    pub joined_at: value::CqlTimestamp,
    pub encrypyed_shared_key: Vec<u8>,
}