// Generated by model_generator.py
#![allow(nonstandard_style)]
use uuid;
use scylla::value;
use scylla::DeserializeRow;
#[derive(Debug, DeserializeRow)]
pub struct Message {
    pub channel_id: uuid::Uuid,
    pub bucket: i64,
    pub message_id: value::CqlTimeuuid,
    pub message_type: i32,
    pub opt_last_edited: Option<value::CqlTimestamp>,
    pub opt_content: Option<String>,
}