// Generated by model_generator.py
#![allow(nonstandard_style)]
use scylla::DeserializeRow;
use scylla::value;
#[derive(Debug, DeserializeRow)]
pub struct MultiusePostAttachment {
    pub multiuse_post_id: value::AllignedCqlTimeuuid,
    pub asset_id: value::AllignedCqlTimeuuid,
}