// Generated by model_generator.py
#![allow(nonstandard_style)]
use scylla::value;
use uuid;
pub struct MultiusePostAttachment {
    pub multiuse_post_id: value::CqlTimeuuid,
    pub asset_id: uuid::Uuid,
}