// Generated by model_generator.py
#![allow(nonstandard_style)]
use uuid;
use scylla::value;
use scylla::DeserializeRow;
#[derive(Debug, DeserializeRow)]
pub struct MultiusePostAttachment {
    pub multiuse_post_id: value::CqlTimeuuid,
    pub asset_id: uuid::Uuid,
}