// Generated by model_generator.py
#![allow(nonstandard_style)]
use crate::protos::plib::AllignedCqlTimeuuid;
use scylla::DeserializeRow;
#[derive(Debug, DeserializeRow, Clone)]
pub struct NeedsGc {
    pub bucket: i64,
    pub object_id: AllignedCqlTimeuuid,
    pub garbage_type: i32,
}