// Generated by model_generator.py
#![allow(nonstandard_style)]
use scylla::DeserializeRow;
use scylla::value;
#[derive(Debug, DeserializeRow)]
pub struct PostLike {
    pub post_id: value::CqlTimeuuid,
    pub liker__user_id: value::CqlTimeuuid,
}