// Generated by model_generator.py
#![allow(nonstandard_style)]
use scylla::value;
use uuid;
pub struct PostComment {
    pub comment_id: value::CqlTimeuuid,
    pub post_id: value::CqlTimeuuid,
    pub author__user_id: uuid::Uuid,
    pub body: String,
    pub last_edited: value::CqlTimestamp,
}