// Generated by model_generator.py
#![allow(nonstandard_style)]
use scylla::DeserializeRow;
use scylla::value;
#[derive(Debug, DeserializeRow)]
pub struct Post {
    pub post_id: value::CqlTimeuuid,
    pub author__user_id: value::CqlTimeuuid,
    pub body: String,
    pub last_edited: value::CqlTimestamp,
    pub opt_likes: Option<i32>,
    pub opt_comments: Option<i32>,
}
impl Post {
    pub fn consume(self) -> (
        value::CqlTimeuuid,
        value::CqlTimeuuid,
        String,
        value::CqlTimestamp,
        Option<i32>,
        Option<i32>,
    ) {
        (
            self.post_id,
            self.author__user_id,
            self.body,
            self.last_edited,
            self.opt_likes,
            self.opt_comments,
        )
    }
}