// Generated by model_generator.py
#![allow(nonstandard_style)]
use crate::protos::plib::AllignedCqlTimeuuid;
use scylla::DeserializeRow;
use scylla::value;
#[derive(Debug, DeserializeRow, Clone)]
pub struct PostV2 {
    pub post_id: AllignedCqlTimeuuid,
    pub author_id: AllignedCqlTimeuuid,
    pub asset_id: AllignedCqlTimeuuid,
    pub timeline_type: i32,
    pub is_private: bool,
    pub post_type: i32,
    pub opt_body: Option<String>,
    pub opt_last_edited: Option<value::CqlTimestamp>,
    pub opt_large: Option<bool>,
}