// Generated by model_generator.py
#![allow(nonstandard_style)]
use scylla::DeserializeRow;
use scylla::value;
#[derive(Debug, DeserializeRow)]
pub struct Post {
    pub post_id: value::CqlTimeuuid,
    pub author_id: value::CqlTimeuuid,
    pub asset_id: value::CqlTimeuuid,
    pub post_type: i32,
    pub content_type: String,
    pub opt_body: Option<String>,
    pub opt_last_edited: Option<value::CqlTimestamp>,
}