// Generated by model_generator.py
#![allow(nonstandard_style)]
use crate::protos::plib::AllignedCqlTimeuuid;
use scylla::DeserializeRow;
use scylla::value;
#[derive(Debug, DeserializeRow, Clone)]
pub struct PostNumCounters {
    pub post_id: AllignedCqlTimeuuid,
    pub post_likes: value::Counter,
    pub post_comments: value::Counter,
}