// Generated by model_generator.py
#![allow(nonstandard_style)]
use scylla::value;
use scylla::DeserializeRow;
#[derive(Debug, DeserializeRow)]
pub struct Post {
    pub post_id: value::CqlTimeuuid,
    pub author__user_id: value::CqlTimeuuid,
    pub body: String,
    pub last_edited: value::CqlTimestamp,
    pub opt_likes: Option<i32>,
    pub opt_comments: Option<i32>,
}