// Generated by model_generator.py
#![allow(nonstandard_style)]
use uuid;
use scylla::value;
use scylla::DeserializeRow;
#[derive(Debug, DeserializeRow)]
pub struct PostComment {
    pub comment_id: value::CqlTimeuuid,
    pub post_id: value::CqlTimeuuid,
    pub author__user_id: uuid::Uuid,
    pub body: String,
    pub opt_last_edited: Option<value::CqlTimestamp>,
}