// Generated by model_generator.py
#![allow(nonstandard_style)]
use crate::protos::plib::AllignedCqlTimeuuid;
use scylla::DeserializeRow;
#[derive(Debug, DeserializeRow, Clone)]
pub struct PostLikeBucketUsed {
    pub post_id: AllignedCqlTimeuuid,
    pub bucket: i64,
}