// Generated by model_generator.py
#![allow(nonstandard_style)]
use scylla::DeserializeRow;
use scylla::value;
#[derive(Debug, DeserializeRow)]
pub struct RelationshipV3 {
    pub user_id_a: value::CqlTimeuuid,
    pub user_id_b: value::CqlTimeuuid,
    pub created_at: value::CqlTimeuuid,
    pub relationship_type: i32,
}