// Generated by model_generator.py
#![allow(nonstandard_style)]
use crate::protos::plib::AllignedCqlTimeuuid;
use scylla::DeserializeRow;
use scylla::value;
#[derive(Debug, DeserializeRow, Clone)]
pub struct RelationshipV2 {
    pub user_id_a: AllignedCqlTimeuuid,
    pub user_id_b: AllignedCqlTimeuuid,
    pub created_at: value::CqlTimestamp,
    pub relationship_type: i32,
}