// Generated by model_generator.py
#![allow(nonstandard_style)]
use scylla::value;
use uuid;
pub struct TemporaryPost {
    pub temp_post_id: value::CqlTimeuuid,
    pub author__user_id: uuid::Uuid,
}