// Generated by model_generator.py
#![allow(nonstandard_style)]
use uuid;
use scylla::value;
use scylla::DeserializeRow;
#[derive(Debug, DeserializeRow)]
pub struct TemporaryPost {
    pub temp_post_id: value::CqlTimeuuid,
    pub author__user_id: uuid::Uuid,
}