// Generated by model_generator.py
#![allow(nonstandard_style)]
use scylla::DeserializeRow;
use scylla::value;
#[derive(Debug, DeserializeRow, Clone)]
pub struct User {
    pub user_id: value::CqlTimeuuid,
    pub username: String,
    pub email: String,
    pub public_key: Vec<u8>,
    pub opt_avatar_asset_id: Option<value::CqlTimeuuid>,
    pub opt_public_profile: Option<bool>,
}