// Generated by model_generator.py
#![allow(nonstandard_style)]
use crate::protos::plib::AllignedCqlTimeuuid;
use scylla::DeserializeRow;
#[derive(Debug, DeserializeRow, Clone)]
pub struct UserTimelineEntry {
    pub user_id: AllignedCqlTimeuuid,
    pub timeline_type: i32,
    pub post_author_id: AllignedCqlTimeuuid,
    pub post_id: AllignedCqlTimeuuid,
    pub entry_type: i32,
}