// Generated by model_generator.py
#![allow(nonstandard_style)]
use scylla::value;
use uuid;
pub struct User {
    pub user_id: value::CqlTimeuuid,
    pub username: String,
    pub public_key: Vec<u8>,
    pub avatar_asset_id: uuid::Uuid,
}