// Generated by model_generator.py
#![allow(nonstandard_style)]
use scylla::DeserializeRow;
use scylla::value;
#[derive(Debug, DeserializeRow)]
pub struct UserTimeline {
    pub user_id: value::AllignedCqlTimeuuid,
    pub timeline_type: i32,
    pub post_id: value::AllignedCqlTimeuuid,
}