// Generated by model_generator.py
#![allow(nonstandard_style)]
use scylla::DeserializeRow;
use scylla::value;
#[derive(Debug, DeserializeRow)]
pub struct UserTimelineEntry {
    pub user_id: value::CqlTimeuuid,
    pub timeline_type: i32,
    pub post_author_id: value::CqlTimeuuid,
    pub post_id: value::CqlTimeuuid,
}