// Generated by model_generator.py
#![allow(nonstandard_style)]
use scylla::DeserializeRow;
use scylla::value;
#[derive(Debug, DeserializeRow, Clone)]
pub struct UserDevice {
    pub user_id: value::CqlTimeuuid,
    pub device_id: value::CqlTimeuuid,
    pub device_name: String,
    pub device_public_key: Vec<u8>,
    pub encrypted_account_key: Vec<u8>,
}