// Generated by model_generator.py
#![allow(nonstandard_style)]
use scylla::DeserializeRow;
use scylla::value;
#[derive(Debug, DeserializeRow)]
pub struct User {
    pub user_id: value::CqlTimeuuid,
    pub username: String,
    pub public_key: Vec<u8>,
    pub opt_avatar_asset_id: Option<uuid::Uuid>,
}
impl User {
    pub fn consume(self) -> (
        value::CqlTimeuuid,
        String,
        Vec<u8>,
        Option<uuid::Uuid>,
    ) {
        (
            self.user_id,
            self.username,
            self.public_key,
            self.opt_avatar_asset_id,
        )
    }
}