// Generated by model_generator.py
#![allow(nonstandard_style)]
use scylla::DeserializeRow;
use scylla::value;
#[derive(Debug, DeserializeRow, Clone)]
pub struct UserLatestPost {
    pub user_id: value::CqlTimeuuid,
    pub last_post_id: value::CqlTimeuuid,
}