// Generated by model_generator.py
#![allow(nonstandard_style)]
use scylla::DeserializeRow;
use scylla::value;
#[derive(Debug, DeserializeRow)]
pub struct UserTimelineMeta {
    pub user_id: value::CqlTimeuuid,
    pub timeline_type: i32,
    pub last_fanned_in_at: value::CqlTimeuuid,
}