// Generated by model_generator.py
#![allow(nonstandard_style)]
use crate::protos::plib::AllignedCqlTimeuuid;
use scylla::DeserializeRow;
#[derive(Debug, DeserializeRow, Clone)]
pub struct UserDevice {
    pub user_id: AllignedCqlTimeuuid,
    pub device_id: AllignedCqlTimeuuid,
    pub device_name: String,
    pub device_public_key: Vec<u8>,
    pub encrypted_account_key: Vec<u8>,
}