// Generated by model_generator.py
#![allow(nonstandard_style)]
use scylla::DeserializeRow;
use scylla::value;
#[derive(Debug, DeserializeRow)]
pub struct UserProfile {
    pub user_id: value::AllignedCqlTimeuuid,
    pub bio: String,
    pub num_friends: i32,
    pub num_followers: i32,
}