// Generated by model_generator.py
#![allow(nonstandard_style)]
use crate::protos::plib::AllignedCqlTimeuuid;
use scylla::DeserializeRow;
#[derive(Debug, DeserializeRow, Clone)]
pub struct UserByUsername {
    pub username: String,
    pub user_id: AllignedCqlTimeuuid,
}