// Generated by model_generator.py
#![allow(nonstandard_style)]
use scylla::DeserializeRow;
use scylla::value;
#[derive(Debug, DeserializeRow, Clone)]
pub struct UserByUsername {
    pub username: String,
    pub user_id: value::CqlTimeuuid,
}