// Generated by model_generator.py
#![allow(nonstandard_style)]
use crate::protos::plib::AllignedCqlTimeuuid;
use scylla::DeserializeRow;
use std::collections::HashSet;
#[derive(Debug, DeserializeRow, Clone)]
pub struct UserTimelineMeta {
    pub user_id: AllignedCqlTimeuuid,
    pub timeline_type: i32,
    pub opt_last_fanned_in_at: Option<i64>,
    pub opt_fanned_in_up_to: Option<AllignedCqlTimeuuid>,
    pub opt_explicit_fan_in_users: Option<HashSet<AllignedCqlTimeuuid>>,
    pub opt_exclude_users: Option<HashSet<AllignedCqlTimeuuid>>,
}