// Generated by model_generator.py
#![allow(nonstandard_style)]
use crate::protos::plib::AllignedCqlTimeuuid;
use scylla::DeserializeRow;
use scylla::value;
#[derive(Debug, DeserializeRow, Clone)]
pub struct UserNumRelationships {
    pub user_id: AllignedCqlTimeuuid,
    pub num_friends: value::Counter,
    pub num_followers: value::Counter,
    pub opt_num_following: Option<value::Counter>,
}