// Generated by model_generator.py
#![allow(nonstandard_style)]
use uuid;
use scylla::value;
use scylla::DeserializeRow;
#[derive(Debug, DeserializeRow)]
pub struct UserDevice {
    pub user_id: uuid::Uuid,
    pub device_id: value::CqlTimeuuid,
    pub device_name: String,
    pub device_public_key: Vec<u8>,
    pub encypted_account_key: Vec<u8>,
}