// Generated by model_generator.py
#![allow(nonstandard_style)]
use scylla::DeserializeRow;
use scylla::value;
#[derive(Debug, DeserializeRow, Clone)]
pub struct UserChannel {
    pub user_id: value::CqlTimeuuid,
    pub channel_id: value::CqlTimeuuid,
    pub opt_last_acked_message_id: Option<value::CqlTimeuuid>,
    pub opt_last_acked_ctr: Option<i64>,
    pub encrypted_channel_key: Vec<u8>,
    pub opt_channel_name: Option<Vec<u8>>,
    pub opt_channel_icon_asset_id: Option<value::CqlTimeuuid>,
}