# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import user_pb2 as user__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in user_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServiceStub(object):
    """User Management (TABLE: account)

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateUser = channel.unary_unary(
                '/dataservices.userproto.UserService/CreateUser',
                request_serializer=user__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=user__pb2.ReadUserResponse.FromString,
                _registered_method=True)
        self.UpdateUser = channel.unary_unary(
                '/dataservices.userproto.UserService/UpdateUser',
                request_serializer=user__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=user__pb2.ReadUserResponse.FromString,
                _registered_method=True)
        self.ReadUser = channel.unary_unary(
                '/dataservices.userproto.UserService/ReadUser',
                request_serializer=user__pb2.ReadUserRequest.SerializeToString,
                response_deserializer=user__pb2.ReadUserResponse.FromString,
                _registered_method=True)
        self.DeleteUser = channel.unary_unary(
                '/dataservices.userproto.UserService/DeleteUser',
                request_serializer=user__pb2.DeleteUserRequest.SerializeToString,
                response_deserializer=user__pb2.DeleteUserResponse.FromString,
                _registered_method=True)
        self.CheckUsername = channel.unary_unary(
                '/dataservices.userproto.UserService/CheckUsername',
                request_serializer=user__pb2.CheckUsernameRequest.SerializeToString,
                response_deserializer=user__pb2.CheckUsernameResponse.FromString,
                _registered_method=True)


class UserServiceServicer(object):
    """User Management (TABLE: account)

    """

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckUsername(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=user__pb2.CreateUserRequest.FromString,
                    response_serializer=user__pb2.ReadUserResponse.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=user__pb2.UpdateUserRequest.FromString,
                    response_serializer=user__pb2.ReadUserResponse.SerializeToString,
            ),
            'ReadUser': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadUser,
                    request_deserializer=user__pb2.ReadUserRequest.FromString,
                    response_serializer=user__pb2.ReadUserResponse.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=user__pb2.DeleteUserRequest.FromString,
                    response_serializer=user__pb2.DeleteUserResponse.SerializeToString,
            ),
            'CheckUsername': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckUsername,
                    request_deserializer=user__pb2.CheckUsernameRequest.FromString,
                    response_serializer=user__pb2.CheckUsernameResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dataservices.userproto.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dataservices.userproto.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """User Management (TABLE: account)

    """

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.userproto.UserService/CreateUser',
            user__pb2.CreateUserRequest.SerializeToString,
            user__pb2.ReadUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.userproto.UserService/UpdateUser',
            user__pb2.UpdateUserRequest.SerializeToString,
            user__pb2.ReadUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.userproto.UserService/ReadUser',
            user__pb2.ReadUserRequest.SerializeToString,
            user__pb2.ReadUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.userproto.UserService/DeleteUser',
            user__pb2.DeleteUserRequest.SerializeToString,
            user__pb2.DeleteUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckUsername(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.userproto.UserService/CheckUsername',
            user__pb2.CheckUsernameRequest.SerializeToString,
            user__pb2.CheckUsernameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class UserDeviceServiceStub(object):
    """User Device Management (TABLE: user_device)

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateDevice = channel.unary_unary(
                '/dataservices.userproto.UserDeviceService/CreateDevice',
                request_serializer=user__pb2.CreateDeviceRequest.SerializeToString,
                response_deserializer=user__pb2.DeviceObjectResponse.FromString,
                _registered_method=True)
        self.ReadDevices = channel.unary_unary(
                '/dataservices.userproto.UserDeviceService/ReadDevices',
                request_serializer=user__pb2.ReadDevicesRequest.SerializeToString,
                response_deserializer=user__pb2.ReadDevicesResponse.FromString,
                _registered_method=True)
        self.UpdateDevice = channel.unary_unary(
                '/dataservices.userproto.UserDeviceService/UpdateDevice',
                request_serializer=user__pb2.UpdateDeviceRequest.SerializeToString,
                response_deserializer=user__pb2.DeviceObjectResponse.FromString,
                _registered_method=True)
        self.DeleteDevice = channel.unary_unary(
                '/dataservices.userproto.UserDeviceService/DeleteDevice',
                request_serializer=user__pb2.DeleteDeviceRequest.SerializeToString,
                response_deserializer=user__pb2.DeleteDeviceResponse.FromString,
                _registered_method=True)


class UserDeviceServiceServicer(object):
    """User Device Management (TABLE: user_device)

    """

    def CreateDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadDevices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserDeviceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDevice,
                    request_deserializer=user__pb2.CreateDeviceRequest.FromString,
                    response_serializer=user__pb2.DeviceObjectResponse.SerializeToString,
            ),
            'ReadDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadDevices,
                    request_deserializer=user__pb2.ReadDevicesRequest.FromString,
                    response_serializer=user__pb2.ReadDevicesResponse.SerializeToString,
            ),
            'UpdateDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDevice,
                    request_deserializer=user__pb2.UpdateDeviceRequest.FromString,
                    response_serializer=user__pb2.DeviceObjectResponse.SerializeToString,
            ),
            'DeleteDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDevice,
                    request_deserializer=user__pb2.DeleteDeviceRequest.FromString,
                    response_serializer=user__pb2.DeleteDeviceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dataservices.userproto.UserDeviceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dataservices.userproto.UserDeviceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserDeviceService(object):
    """User Device Management (TABLE: user_device)

    """

    @staticmethod
    def CreateDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.userproto.UserDeviceService/CreateDevice',
            user__pb2.CreateDeviceRequest.SerializeToString,
            user__pb2.DeviceObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.userproto.UserDeviceService/ReadDevices',
            user__pb2.ReadDevicesRequest.SerializeToString,
            user__pb2.ReadDevicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.userproto.UserDeviceService/UpdateDevice',
            user__pb2.UpdateDeviceRequest.SerializeToString,
            user__pb2.DeviceObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.userproto.UserDeviceService/DeleteDevice',
            user__pb2.DeleteDeviceRequest.SerializeToString,
            user__pb2.DeleteDeviceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class UserRelationshipServiceStub(object):
    """relationship management (TABLE: friendship, friendship_request, blocked_user)

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateFriendshipInvite = channel.unary_unary(
                '/dataservices.userproto.UserRelationshipService/CreateFriendshipInvite',
                request_serializer=user__pb2.CreateFriendshipInviteRequest.SerializeToString,
                response_deserializer=user__pb2.FriendshipInviteResponse.FromString,
                _registered_method=True)
        self.ReadRecvFriendshipInvites = channel.unary_unary(
                '/dataservices.userproto.UserRelationshipService/ReadRecvFriendshipInvites',
                request_serializer=user__pb2.ReadRecvFriendshipInvitesRequest.SerializeToString,
                response_deserializer=user__pb2.ReadRecvFriendshipInviteResponse.FromString,
                _registered_method=True)
        self.ReadSentFriendshipInvites = channel.unary_unary(
                '/dataservices.userproto.UserRelationshipService/ReadSentFriendshipInvites',
                request_serializer=user__pb2.ReadSentFriendshipInvitesRequest.SerializeToString,
                response_deserializer=user__pb2.ReadSentFriendshipInviteResponse.FromString,
                _registered_method=True)
        self.DeleteFriendshipInvite = channel.unary_unary(
                '/dataservices.userproto.UserRelationshipService/DeleteFriendshipInvite',
                request_serializer=user__pb2.DeleteFriendshipInviteRequest.SerializeToString,
                response_deserializer=user__pb2.DeleteFriendshipInviteResponse.FromString,
                _registered_method=True)
        self.CreateFriendship = channel.unary_unary(
                '/dataservices.userproto.UserRelationshipService/CreateFriendship',
                request_serializer=user__pb2.CreateFriendshipRequest.SerializeToString,
                response_deserializer=user__pb2.FriendshipObjectResponse.FromString,
                _registered_method=True)
        self.ReadFriendships = channel.unary_unary(
                '/dataservices.userproto.UserRelationshipService/ReadFriendships',
                request_serializer=user__pb2.ReadFriendshipsRequest.SerializeToString,
                response_deserializer=user__pb2.ReadFriendshipsResponse.FromString,
                _registered_method=True)
        self.DeleteFriendship = channel.unary_unary(
                '/dataservices.userproto.UserRelationshipService/DeleteFriendship',
                request_serializer=user__pb2.DeleteFriendshipRequest.SerializeToString,
                response_deserializer=user__pb2.DeleteFriendshipResponse.FromString,
                _registered_method=True)
        self.CreateBlockedUser = channel.unary_unary(
                '/dataservices.userproto.UserRelationshipService/CreateBlockedUser',
                request_serializer=user__pb2.CreateBlockedUserRequest.SerializeToString,
                response_deserializer=user__pb2.BlockedUserObjectResponse.FromString,
                _registered_method=True)
        self.ReadBlockedUsers = channel.unary_unary(
                '/dataservices.userproto.UserRelationshipService/ReadBlockedUsers',
                request_serializer=user__pb2.ReadBlockedUsersRequest.SerializeToString,
                response_deserializer=user__pb2.ReadBlockedUsersResponse.FromString,
                _registered_method=True)
        self.ReadBlockedUser = channel.unary_unary(
                '/dataservices.userproto.UserRelationshipService/ReadBlockedUser',
                request_serializer=user__pb2.ReadBlockedUserRequest.SerializeToString,
                response_deserializer=user__pb2.BlockedUserObjectResponse.FromString,
                _registered_method=True)
        self.DeleteBlockedUser = channel.unary_unary(
                '/dataservices.userproto.UserRelationshipService/DeleteBlockedUser',
                request_serializer=user__pb2.DeleteBlockedUserRequest.SerializeToString,
                response_deserializer=user__pb2.DeleteBlockedUserResponse.FromString,
                _registered_method=True)


class UserRelationshipServiceServicer(object):
    """relationship management (TABLE: friendship, friendship_request, blocked_user)

    """

    def CreateFriendshipInvite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadRecvFriendshipInvites(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadSentFriendshipInvites(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFriendshipInvite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateFriendship(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFriendships(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFriendship(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBlockedUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadBlockedUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadBlockedUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBlockedUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserRelationshipServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateFriendshipInvite': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFriendshipInvite,
                    request_deserializer=user__pb2.CreateFriendshipInviteRequest.FromString,
                    response_serializer=user__pb2.FriendshipInviteResponse.SerializeToString,
            ),
            'ReadRecvFriendshipInvites': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadRecvFriendshipInvites,
                    request_deserializer=user__pb2.ReadRecvFriendshipInvitesRequest.FromString,
                    response_serializer=user__pb2.ReadRecvFriendshipInviteResponse.SerializeToString,
            ),
            'ReadSentFriendshipInvites': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadSentFriendshipInvites,
                    request_deserializer=user__pb2.ReadSentFriendshipInvitesRequest.FromString,
                    response_serializer=user__pb2.ReadSentFriendshipInviteResponse.SerializeToString,
            ),
            'DeleteFriendshipInvite': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFriendshipInvite,
                    request_deserializer=user__pb2.DeleteFriendshipInviteRequest.FromString,
                    response_serializer=user__pb2.DeleteFriendshipInviteResponse.SerializeToString,
            ),
            'CreateFriendship': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFriendship,
                    request_deserializer=user__pb2.CreateFriendshipRequest.FromString,
                    response_serializer=user__pb2.FriendshipObjectResponse.SerializeToString,
            ),
            'ReadFriendships': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadFriendships,
                    request_deserializer=user__pb2.ReadFriendshipsRequest.FromString,
                    response_serializer=user__pb2.ReadFriendshipsResponse.SerializeToString,
            ),
            'DeleteFriendship': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFriendship,
                    request_deserializer=user__pb2.DeleteFriendshipRequest.FromString,
                    response_serializer=user__pb2.DeleteFriendshipResponse.SerializeToString,
            ),
            'CreateBlockedUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBlockedUser,
                    request_deserializer=user__pb2.CreateBlockedUserRequest.FromString,
                    response_serializer=user__pb2.BlockedUserObjectResponse.SerializeToString,
            ),
            'ReadBlockedUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadBlockedUsers,
                    request_deserializer=user__pb2.ReadBlockedUsersRequest.FromString,
                    response_serializer=user__pb2.ReadBlockedUsersResponse.SerializeToString,
            ),
            'ReadBlockedUser': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadBlockedUser,
                    request_deserializer=user__pb2.ReadBlockedUserRequest.FromString,
                    response_serializer=user__pb2.BlockedUserObjectResponse.SerializeToString,
            ),
            'DeleteBlockedUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBlockedUser,
                    request_deserializer=user__pb2.DeleteBlockedUserRequest.FromString,
                    response_serializer=user__pb2.DeleteBlockedUserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dataservices.userproto.UserRelationshipService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dataservices.userproto.UserRelationshipService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserRelationshipService(object):
    """relationship management (TABLE: friendship, friendship_request, blocked_user)

    """

    @staticmethod
    def CreateFriendshipInvite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.userproto.UserRelationshipService/CreateFriendshipInvite',
            user__pb2.CreateFriendshipInviteRequest.SerializeToString,
            user__pb2.FriendshipInviteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadRecvFriendshipInvites(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.userproto.UserRelationshipService/ReadRecvFriendshipInvites',
            user__pb2.ReadRecvFriendshipInvitesRequest.SerializeToString,
            user__pb2.ReadRecvFriendshipInviteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadSentFriendshipInvites(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.userproto.UserRelationshipService/ReadSentFriendshipInvites',
            user__pb2.ReadSentFriendshipInvitesRequest.SerializeToString,
            user__pb2.ReadSentFriendshipInviteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFriendshipInvite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.userproto.UserRelationshipService/DeleteFriendshipInvite',
            user__pb2.DeleteFriendshipInviteRequest.SerializeToString,
            user__pb2.DeleteFriendshipInviteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateFriendship(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.userproto.UserRelationshipService/CreateFriendship',
            user__pb2.CreateFriendshipRequest.SerializeToString,
            user__pb2.FriendshipObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadFriendships(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.userproto.UserRelationshipService/ReadFriendships',
            user__pb2.ReadFriendshipsRequest.SerializeToString,
            user__pb2.ReadFriendshipsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFriendship(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.userproto.UserRelationshipService/DeleteFriendship',
            user__pb2.DeleteFriendshipRequest.SerializeToString,
            user__pb2.DeleteFriendshipResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBlockedUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.userproto.UserRelationshipService/CreateBlockedUser',
            user__pb2.CreateBlockedUserRequest.SerializeToString,
            user__pb2.BlockedUserObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadBlockedUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.userproto.UserRelationshipService/ReadBlockedUsers',
            user__pb2.ReadBlockedUsersRequest.SerializeToString,
            user__pb2.ReadBlockedUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadBlockedUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.userproto.UserRelationshipService/ReadBlockedUser',
            user__pb2.ReadBlockedUserRequest.SerializeToString,
            user__pb2.BlockedUserObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteBlockedUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.userproto.UserRelationshipService/DeleteBlockedUser',
            user__pb2.DeleteBlockedUserRequest.SerializeToString,
            user__pb2.DeleteBlockedUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
