syntax = "proto3";

package dataservices.channelproto;

import "plib.proto";
import "google/protobuf/field_mask.proto";


service ChannelService {
    rpc CreateChannel (CreateChannelRequest) returns (ChannelObjectResponse);
    rpc ReadChannel (ReadChannelRequest) returns (ChannelObjectResponse);
    rpc UpdateChannel (UpdateChannelRequest) returns (ChannelObjectResponse);
    rpc DeleteChannel (ReadChannelRequest) returns (DeleteChannelResponse);

    rpc AddChannelMembers (AddChannelMembersRequest) returns (AddChannelMembersResponse);
    rpc RemoveChannelMembers (RemoveChannelMembersRequest) returns (RemoveChannelMembersResponse);
    rpc UpdateChannelMember (UpdateChannelMemberRequest) returns (UpdateChannelMemberResponse);

    rpc GetUserChannels (GetUserChannelsRequest) returns (UserChannelsResponse);

}

message CreateChannelRequest {
    int32 channel_type = 1;
    optional bytes opt_channel_name = 2;
    optional plib.pUUID opt_channel_icon_asset_id = 3; 
}

message UpdateChannelRequest {
    plib.pUUID channel_id = 1;
    optional bytes opt_channel_name = 2;
    optional plib.pUUID opt_channel_icon_asset_id = 3;
    google.protobuf.FieldMask update_mask = 4;
    repeated plib.pUUID members_to_update = 5;
    optional int64 last_bucket = 6;
}

message ReadChannelRequest {
    plib.pUUID channel_id = 1;
}

message DeleteChannelRequest {
    plib.pUUID channel_id = 1;
}

message DeleteChannelResponse {}

message ChannelObjectResponse {
    plib.pUUID channel_id = 1;
    int32 channel_type = 2;
    int64 latest_bucket = 6;
    optional bytes opt_channel_name = 3;
    repeated plib.pUUID channel_members = 4;
    optional plib.pUUID opt_channel_icon_asset_id = 5;
}

message GetUserChannelsRequest {
    plib.pUUID user_id = 1;
}

message UserChannelsResponse {
    repeated ChannelMemberObject channels = 1;
}

message AddChannelMemberRequest {
    plib.pUUID user_id = 1;
    bytes encrypted_channel_key = 2;
}

message ChannelMemberObject {
    plib.pUUID user_id = 1;
    plib.pUUID channel_id = 2;
    bytes encrypted_channel_key = 3;
    optional plib.pUUID last_acked_message_id = 4;
    optional bytes opt_channel_name = 5;
    optional plib.pUUID opt_channel_icon_asset_id = 6;
}

message AddChannelMembersRequest {
    plib.pUUID channel_id = 1;
    CreateChannelRequest channel = 3;
    repeated AddChannelMemberRequest requests = 2;
}

message AddChannelMembersResponse {}

message RemoveChannelMembersRequest {
    plib.pUUID channel_id = 1;
    repeated plib.pUUID members = 2;
}

message RemoveChannelMembersResponse {}

message UpdateChannelMemberRequest {
    plib.pUUID user_id = 1;
    plib.pUUID channel_id = 2;
    optional plib.pUUID last_acked_message_id = 3;
}

message UpdateChannelMemberResponse {}