syntax = "proto3";

package dataservices.messageproto;
import "plib.proto";
import "google/protobuf/field_mask.proto";
import "google/protobuf/wrappers.proto";


service MessageService {
    rpc CreateMessage (CreateMessageRequest) returns (MessageObject);
    rpc UpdateMessage (UpdateMessageRequest) returns (MessageObject);
    rpc ReadMessage (ReadMessageRequest) returns (MessageObject);
    rpc DeleteMessage (DeleteMessageRequest) returns (DeleteMessageResponse);

    rpc ReadMessages (ReadMessagesRequest) returns (ReadMessagesResponse);
}


message CreateMessageRequest {
    plib.pUUID channel_id = 1;
    int32 message_type = 2;
    plib.pUUID author_id = 6;
    optional int64 opt_last_edited = 3;
    optional bytes opt_content = 4;
    optional bytes opt_additional_content = 8;
    optional google.protobuf.BoolValue request_asset = 5;
    optional plib.pUUID opt_in_reply_to = 7;
}

message MessageObject {
    plib.pUUID channel_id = 1;
    int64 bucket = 2;
    plib.pUUID message_id = 3;
    int32 message_type = 4;
    plib.pUUID author_id = 8;
    optional int64 opt_last_edited = 5;
    optional bytes opt_content = 6;
    optional bytes opt_additional_content = 10;
    optional plib.pUUID opt_attachment_asset_id = 7;
    optional plib.pUUID opt_in_reply_to = 9;
}

message UpdateMessageRequest {
    plib.pUUID channel_id = 1;
    plib.pUUID message_id = 3;
    google.protobuf.BytesValue content = 6;
    google.protobuf.Int32Value message_type = 7;
}

message ReadMessageRequest {
    plib.pUUID channel_id = 1;
    plib.pUUID message_id = 2;
}

message DeleteMessageRequest {
    plib.pUUID channel_id = 1;
    plib.pUUID message_id = 2;
}

message DeleteMessageResponse {}

message ReadMessagesRequest {
    plib.pUUID channel_id = 1;
    optional plib.pUUID before = 2;
    int32 count = 3;
    int64 latest_bucket = 4;
}

message ReadMessagesResponse {
    repeated MessageObject messages = 1;
}