syntax = "proto3";

package dataservices.postproto;
import "plib.proto";
import "google/protobuf/wrappers.proto";
import "google/protobuf/field_mask.proto";

service PostService {
    rpc CreatePost (CreatePostRequest) returns (PostResponse);
    rpc ReadPost (ReadPostRequest) returns (PostResponse);
    rpc UpdatePost (UpdatePostRequest) returns (PostResponse);
    rpc DeletePost (DeletePostRequest) returns (DeletePostResponse);

    rpc ReadManyPosts (ReadManyPostsRequest) returns (ManyPostsResponse);
    rpc ReadUserPosts (ReadUserPostsRequest) returns (UserPostsResponse);
    rpc ReadUsersDehydratedPosts (ReadUsersDehydratedPostsRequest) returns (UsersDehydratedPostsResponse);

    rpc LikePost (LikePostRequest) returns (LikePostResponse);
    rpc UnlikePost (LikePostRequest) returns (LikePostResponse);
}

message CreatePostRequest {
    plib.pUUID author_id = 1;
    int32 post_type = 2;
    optional string body = 4;
    int32 timeline_type = 5;
}

message PostResponse {
    plib.pUUID post_id = 1;
    plib.pUUID author_id = 2;
    plib.pUUID asset_id = 3;
    int32 post_type = 4;
    optional google.protobuf.StringValue body = 6;
    optional google.protobuf.Int64Value last_edited = 7;
    int64 num_comments = 8;
    int64 num_likes = 9;
    bool is_private = 10;
}

message ReadPostRequest {
    plib.pUUID post_id = 1;
    plib.pUUID author_id = 2;
    int32 timeline_type = 3;
}

message UpdatePostRequest {
    plib.pUUID author_id = 1;
    plib.pUUID post_id = 2;
    int32 timeline_type = 7;
    google.protobuf.FieldMask field_mask = 3;
    optional google.protobuf.StringValue body = 4;
    optional google.protobuf.BoolValue is_private = 6;
}

message DeletePostRequest {
    plib.pUUID post_id = 1;
    plib.pUUID author_id = 2;
    int32 timeline_type = 3;
}

message DeletePostResponse {}

message ReadManyPostsRequest {
    repeated ReadPostRequest requests = 1;
}

message ManyPostsResponse {
    repeated PostResponse responses = 1;
}

message ReadUserPostsRequest {
    plib.pUUID author_id = 1;
    int32 limit = 2;
    int32 timeline_type = 3;
    optional plib.pUUID before = 4;
}

message UserPostsResponse {
    repeated PostResponse posts = 1;
}

// extra dehydrated request for fanning into timeline
// as timeline posts are hydrated separately
message ReadUsersDehydratedPostsRequest {
    repeated plib.pUUID author_ids = 1;
    int32 limit = 2;
    int32 timeline_type = 3;
    optional plib.pUUID before = 4;
    int64 after = 5;
}

message UsersDehydratedPostsResponse {
    repeated DehydratedPosts posts = 1;
}

message DehydratedPosts {
    plib.pUUID user_id = 1;
    repeated plib.pUUID post_ids = 2;
}

message LikePostRequest {
    plib.pUUID post_id = 1;
    plib.pUUID liker_id = 2;
}

message LikePostResponse {}
