syntax = "proto3";

package dataservices.postproto;
import "plib.proto";
import "google/protobuf/wrappers.proto";
import "google/protobuf/field_mask.proto";

service PostService {
    rpc CreatePost (CreatePostRequest) returns (ReadPostResponse);
    rpc ReadPost (ReadPostRequest) returns (ReadPostResponse);
    rpc UpdatePost (UpdatePostRequest) returns (ReadPostResponse);
    rpc DeletePost (DeletePostRequest) returns (DeletePostResponse);

    rpc ReadManyPosts (ReadManyPostsRequest) returns (ReadManyPostsResponse);
    rpc ReadUserPosts (ReadUserPostsRequest) returns (ReadUserPostsResponse);
}

message CreatePostRequest {
    plib.pUUID author_id = 1;
    uint32 post_type = 2;
    string content_type = 3;
    optional string body = 4;
}

message ReadPostResponse {
    plib.pUUID post_id = 1;
    plib.pUUID author_id = 2;
    plib.pUUID asset_id = 3;
    int32 post_type = 4;
    string content_type = 5;
    optional google.protobuf.StringValue body = 6;
    optional google.protobuf.Int64Value last_edited = 7;
    int64 num_comments = 8;
    int64 num_likes = 9;
}

message ReadPostRequest {
    plib.pUUID post_id = 1;
    plib.pUUID author_id = 2;
}

message UpdatePostRequest {
    plib.pUUID author_id = 1;
    plib.pUUID post_id = 2;
    optional google.protobuf.StringValue body = 3;
    optional google.protobuf.Int32Value post_type = 4;
    google.protobuf.FieldMask field_mask = 5;
}

message DeletePostRequest {
    plib.pUUID post_id = 1;
    plib.pUUID author_id = 2;
}

message DeletePostResponse {}

message ReadManyPostsRequest {
    repeated ReadPostRequest requests = 1;
}

message ReadManyPostsResponse {
    repeated ReadPostResponse responses = 1;
}

message ReadUserPostsRequest {
    plib.pUUID author_id = 1;
    int32 limit = 2;
    plib.pUUID before = 3;
}

message ReadUserPostsResponse {
    repeated ReadPostResponse posts = 1;
}