syntax = "proto3";

package dataservices.userproto;


// User Management (TABLE: account)

service UserService {
    rpc CreateUser (CreateUserRequest) returns (ReadUserResponse);
    rpc UpdateUser (UpdateUserRequest) returns (ReadUserResponse);
    rpc ReadUser (ReadUserRequest) returns (ReadUserResponse);
    rpc DeleteUser (DeleteUserRequest) returns (DeleteUserResponse);


}
message ReadUserRequest {
    bytes user_id = 1;
}
message ReadUserResponse {
    bytes user_id = 1;
    bytes avatar_asset_id = 2;
    int64 created_at = 3;
    string public_key = 4;
    string username = 5;
}

message CreateUserRequest {
    string username = 1;
    string public_key = 2;
}

message UpdateUserRequest {
    bytes user_id = 1;
    string username = 2;
    bytes avatar_asset_id = 3;
}

message DeleteUserRequest {
    bytes user_id = 1;
}

message DeleteUserResponse {}


// User Device Management (TABLE: user_device)

service UserDeviceService {
    rpc CreateDevice (CreateDeviceRequest) returns (DeviceObjectResponse);
    rpc ReadDevices (ReadDevicesRequest) returns (ReadDevicesResponse);
    rpc UpdateDevice (UpdateDeviceRequest) returns (DeviceObjectResponse);
    rpc DeleteDevice (DeleteDeviceRequest) returns (DeleteDeviceResponse);
}


message CreateDeviceRequest {
    bytes user_id = 1;
    string device_name = 2;
    string public_key = 3;
    string encrypted_account_private_key = 4;
}

message DeviceObjectResponse {
    bytes device_id = 1;
    bytes user_id = 2;
    string device_name = 3;
    string device_type = 4;
    string device_public_key = 5;
    int64 created_at = 6;
    string encrypted_account_private_key = 7;
}


message ReadDevicesRequest {
    bytes user_id = 1;
    bool count_only = 2;
}
message ReadDevicesResponse {
    int32 device_count = 1;
    repeated DeviceObjectResponse devices = 2;
}

message UpdateDeviceRequest {
    bytes device_id = 1;
    string device_name = 2;
    string device_type = 3;
    string encrypted_account_private_key = 4;
}
message DeleteDeviceRequest {
    bytes device_id = 1;
}
message DeleteDeviceResponse {}

// relationship management (TABLE: friendship, friendship_request, blocked_user)


service UserRelationshipService {
    rpc CreateFriendshipInvite (CreateFriendshipInviteRequest) returns (FriendshipInviteResponse);
    rpc ReadRecvFriendshipInvites (ReadRecvFriendshipInvitesRequest) returns (ReadRecvFriendshipInviteResponse);
    rpc ReadSentFriendshipInvites (ReadSentFriendshipInvitesRequest) returns (ReadSentFriendshipInviteResponse);
    rpc DeleteFriendshipInvite (DeleteFriendshipInviteRequest) returns (DeleteFriendshipInviteResponse);

    rpc CreateFriendship (CreateFriendshipRequest) returns (FriendshipObjectResponse);
    rpc ReadFriendships (ReadFriendshipsRequest) returns (ReadFriendshipsResponse);
    rpc DeleteFriendship (DeleteFriendshipRequest) returns (DeleteFriendshipResponse);

    rpc CreateBlockedUser (CreateBlockedUserRequest) returns (BlockedUserObjectResponse);
    rpc ReadBlockedUsers (ReadBlockedUsersRequest) returns (ReadBlockedUsersResponse);
    rpc ReadBlockedUser (ReadBlockedUserRequest) returns (BlockedUserObjectResponse);
    rpc DeleteBlockedUser (DeleteBlockedUserRequest) returns (DeleteBlockedUserResponse);
}

// create friendship invite
message CreateFriendshipInviteRequest {
    bytes from_user_id = 1;
    bytes to_user_id = 2;
}

message FriendshipInviteResponse {}

message FriendshipInviteObject {
    bytes user_id = 1;
}

// read received friendship invites
message ReadRecvFriendshipInvitesRequest {
    bytes to_user_id = 1;
}

message ReadRecvFriendshipInviteResponse {
    repeated FriendshipInviteObject invites = 1;
}

// read sent friendship invites
message ReadSentFriendshipInvitesRequest {
    bytes from_user_id = 1;
}

message ReadSentFriendshipInviteResponse {
    repeated FriendshipInviteObject invites = 1;
}

// remove friendship invite (decline or revoke)
message DeleteFriendshipInviteRequest {
    bytes from_user_id = 1;
    bytes to_user_id = 2;
}

message DeleteFriendshipInviteResponse {}

// create friendship
message CreateFriendshipRequest {
    bytes user_id_1 = 1;
    bytes user_id_2 = 2;
}

message FriendshipObjectResponse {
    bytes user_id_1 = 1;
    bytes user_id_2 = 2;
    int64 created_at = 3;
}

// read friendships

message ReadFriendshipsRequest {
    bytes user_id = 1;
}

message FriendshipsObjectResponse {
    bytes user_id = 1;
    int64 created_at = 2;
}

message ReadFriendshipsResponse {
    repeated FriendshipsObjectResponse friendships = 1;
}

// delete friendship
message DeleteFriendshipRequest {
    bytes user_id_1 = 1;
    bytes user_id_2 = 2;
}
message DeleteFriendshipResponse {}

// create blocked user
message CreateBlockedUserRequest {
    bytes blocker_user_id = 1;
    bytes blocked_user_id = 2;
}

message BlockedUserObjectResponse {
    bytes blocker_user_id = 1;
    bytes blocked_user_id = 2;
}

// read blocked users
message ReadBlockedUsersRequest {
    bytes blocker_user_id = 1;
}

message BlockedUsersObjectResponse {
    bytes blocked_user_id = 2;
}

message ReadBlockedUsersResponse {
    repeated BlockedUsersObjectResponse blocked_users = 1;
}

// read blocked user
message ReadBlockedUserRequest {
    bytes blocker_user_id = 1;
    bytes blocked_user_id = 2;
}

// unblock blocked user
message DeleteBlockedUserRequest {
    bytes blocker_user_id = 1;
    bytes blocked_user_id = 2;
}
message DeleteBlockedUserResponse {}





