syntax = "proto3";

package dataservices.userproto;

import "plib.proto";

// User Management (TABLE: account)

service UserService {
    rpc CreateUser (CreateUserRequest) returns (ReadUserResponse);
    rpc UpdateUser (UpdateUserRequest) returns (ReadUserResponse);
    rpc ReadUser (ReadUserRequest) returns (ReadUserResponse);
    rpc ReadUserByUsername (ReadUserByUsernameRequest) returns (ReadUserResponse);
    rpc DeleteUser (DeleteUserRequest) returns (DeleteUserResponse);
    rpc CheckUsername (ReadUserByUsernameRequest) returns (CheckUsernameResponse);


}
message ReadUserRequest {
    plib.pUUID user_id = 1;
}

message ReadUserByUsernameRequest {
    string username = 1;
}

message ReadUserResponse {
    plib.pUUID user_id = 1;
    optional plib.pUUID avatar_asset_id = 2;
    bytes public_key = 3;
    string username = 4;
    string email = 5;
}

message CreateUserRequest {
    string username = 1;
    string email = 2;
    bytes public_key = 3;
}

message UpdateUserRequest {
    plib.pUUID user_id = 1;
    optional string username = 2;
    optional plib.pUUID avatar_asset_id = 3;
}

message DeleteUserRequest {
    plib.pUUID user_id = 1;
}

message DeleteUserResponse {}


message CheckUsernameResponse {}


// User Device Management (TABLE: user_device)

service UserDeviceService {
    rpc CreateDevice (CreateDeviceRequest) returns (DeviceObjectResponse);
    rpc ReadDevices (ReadDevicesRequest) returns (ReadDevicesResponse);
    rpc UpdateDevice (UpdateDeviceRequest) returns (DeviceObjectResponse);
    rpc DeleteDevice (DeleteDeviceRequest) returns (DeleteDeviceResponse);
}


message CreateDeviceRequest {
    plib.pUUID user_id = 1;
    string device_name = 2;
    bytes public_key = 3;
    bytes encrypted_account_key = 4;
}

message DeviceObjectResponse {
    plib.pUUID device_id = 1;
    plib.pUUID user_id = 2;
    string device_name = 3;
    bytes device_public_key = 5;
    bytes encrypted_account_key = 6;
}


message ReadDevicesRequest {
    plib.pUUID user_id = 1;
    optional bool count_only = 2;
}
message ReadDevicesResponse {
    int32 device_count = 1;
    repeated DeviceObjectResponse devices = 2;
}

message UpdateDeviceRequest {
    plib.pUUID user_id = 1;
    plib.pUUID device_id = 2;
    optional string device_name = 3;
    optional bytes device_public_key = 4;
    optional bytes encrypted_account_key = 5;
}
message DeleteDeviceRequest {
    plib.pUUID user_id = 1;
    plib.pUUID device_id = 2;
}
message DeleteDeviceResponse {}

// relationship management (TABLE: friendship, friendship_request, blocked_user)


service UserRelationshipService {
    rpc CreateFriendshipInvite (CreateFriendshipInviteRequest) returns (FriendshipInviteResponse);
    rpc ReadRecvFriendshipInvites (ReadRecvFriendshipInvitesRequest) returns (ReadRecvFriendshipInviteResponse);
    rpc ReadSentFriendshipInvites (ReadSentFriendshipInvitesRequest) returns (ReadSentFriendshipInviteResponse);
    rpc DeleteFriendshipInvite (DeleteFriendshipInviteRequest) returns (DeleteFriendshipInviteResponse);

    rpc CreateFriendship (CreateFriendshipRequest) returns (FriendshipObjectResponse);
    rpc ReadFriendships (ReadFriendshipsRequest) returns (ReadFriendshipsResponse);
    rpc DeleteFriendship (DeleteFriendshipRequest) returns (DeleteFriendshipResponse);

    rpc CreateBlockedUser (CreateBlockedUserRequest) returns (BlockedUserObjectResponse);
    rpc ReadBlockedUsers (ReadBlockedUsersRequest) returns (ReadBlockedUsersResponse);
    rpc ReadBlockedUser (ReadBlockedUserRequest) returns (BlockedUserObjectResponse);
    rpc DeleteBlockedUser (DeleteBlockedUserRequest) returns (DeleteBlockedUserResponse);
}

// create friendship invite
message CreateFriendshipInviteRequest {
    plib.pUUID from_user_id = 1;
    plib.pUUID to_user_id = 2;
}

message FriendshipInviteResponse {}

message FriendshipInviteObject {
    plib.pUUID user_id = 1;
}

// read received friendship invites
message ReadRecvFriendshipInvitesRequest {
    plib.pUUID to_user_id = 1;
}

message ReadRecvFriendshipInviteResponse {
    repeated FriendshipInviteObject invites = 1;
}

// read sent friendship invites
message ReadSentFriendshipInvitesRequest {
    plib.pUUID from_user_id = 1;
}

message ReadSentFriendshipInviteResponse {
    repeated FriendshipInviteObject invites = 1;
}

// remove friendship invite (decline or revoke)
message DeleteFriendshipInviteRequest {
    plib.pUUID from_user_id = 1;
    plib.pUUID to_user_id = 2;
}

message DeleteFriendshipInviteResponse {}

// create friendship
message CreateFriendshipRequest {
    plib.pUUID user_id_1 = 1;
    plib.pUUID user_id_2 = 2;
}

message FriendshipObjectResponse {
    plib.pUUID user_id_1 = 1;
    plib.pUUID user_id_2 = 2;
    int64 created_at = 3;
}

// read friendships

message ReadFriendshipsRequest {
    plib.pUUID user_id = 1;
}

message FriendshipsObjectResponse {
    plib.pUUID user_id = 1;
    int64 created_at = 2;
}

message ReadFriendshipsResponse {
    repeated FriendshipsObjectResponse friendships = 1;
}

// delete friendship
message DeleteFriendshipRequest {
    plib.pUUID user_id_1 = 1;
    plib.pUUID user_id_2 = 2;
}
message DeleteFriendshipResponse {}

// create blocked user
message CreateBlockedUserRequest {
    plib.pUUID blocker_user_id = 1;
    plib.pUUID blocked_user_id = 2;
}

message BlockedUserObjectResponse {
    plib.pUUID blocker_user_id = 1;
    plib.pUUID blocked_user_id = 2;
}

// read blocked users
message ReadBlockedUsersRequest {
    plib.pUUID blocker_user_id = 1;
}

message BlockedUsersObjectResponse {
    plib.pUUID blocked_user_id = 2;
}

message ReadBlockedUsersResponse {
    repeated BlockedUsersObjectResponse blocked_users = 1;
}

// read blocked user
message ReadBlockedUserRequest {
    plib.pUUID blocker_user_id = 1;
    plib.pUUID blocked_user_id = 2;
}

// unblock blocked user
message DeleteBlockedUserRequest {
    plib.pUUID blocker_user_id = 1;
    plib.pUUID blocked_user_id = 2;
}
message DeleteBlockedUserResponse {}





