syntax = "proto3";

package dataservices.userproto;

import "plib.proto";

// User Management (TABLE: account)

service UserService {
    rpc CreateUser (CreateUserRequest) returns (ReadUserResponse);
    rpc UpdateUser (UpdateUserRequest) returns (ReadUserResponse);
    rpc ReadUser (ReadUserRequest) returns (ReadUserResponse);
    rpc ReadUserByUsername (ReadUserByUsernameRequest) returns (ReadUserResponse);
    rpc DeleteUser (DeleteUserRequest) returns (DeleteUserResponse);
    rpc CheckUsername (ReadUserByUsernameRequest) returns (CheckUsernameResponse);

    rpc UsernameSearcher (UsernameSearch) returns (UsernameSearchResponse);

}
message ReadUserRequest {
    plib.pUUID user_id = 1;
}

message ReadUserByUsernameRequest {
    string username = 1;
}

message ReadUserResponse {
    plib.pUUID user_id = 1;
    optional plib.pUUID avatar_asset_id = 2;
    bytes public_key = 3;
    string username = 4;
    string email = 5;
}

message CreateUserRequest {
    string username = 1;
    string email = 2;
    bytes public_key = 3;
}

message UpdateUserRequest {
    plib.pUUID user_id = 1;
    optional string username = 2;
    optional plib.pUUID avatar_asset_id = 3;
}

message DeleteUserRequest {
    plib.pUUID user_id = 1;
}

message DeleteUserResponse {}


message CheckUsernameResponse {}

message UsernameSearch {
    string query = 1;
}

message UsernameSearchResponse {
    repeated UserSearchEntry users = 1;
}

message UserSearchEntry {
    plib.pUUID user_id = 1;
    optional plib.pUUID opt_avatar_asset_id = 2;
    string username = 3;
    bytes public_key = 4;
}



// User Device Management (TABLE: user_device)

service UserDeviceService {
    rpc CreateDevice (CreateDeviceRequest) returns (DeviceObjectResponse);
    rpc ReadDevices (ReadDevicesRequest) returns (ReadDevicesResponse);
    rpc ReadDevice (ReadDeviceRequest) returns (DeviceObjectResponse);
    rpc UpdateDevice (UpdateDeviceRequest) returns (DeviceObjectResponse);
    rpc DeleteDevice (DeleteDeviceRequest) returns (DeleteDeviceResponse);
}


message CreateDeviceRequest {
    plib.pUUID user_id = 1;
    string device_name = 2;
    bytes public_key = 3;
    bytes encrypted_account_key = 4;
}

message ReadDeviceRequest {
    plib.pUUID device_id = 1;
    plib.pUUID user_id = 2;
}

message DeviceObjectResponse {
    plib.pUUID device_id = 1;
    plib.pUUID user_id = 2;
    string device_name = 3;
    bytes device_public_key = 5;
    bytes encrypted_account_key = 6;
}


message ReadDevicesRequest {
    plib.pUUID user_id = 1;
    optional bool count_only = 2;
}
message ReadDevicesResponse {
    int32 device_count = 1;
    repeated DeviceObjectResponse devices = 2;
}

message UpdateDeviceRequest {
    plib.pUUID user_id = 1;
    plib.pUUID device_id = 2;
    optional string device_name = 3;
    optional bytes device_public_key = 4;
    optional bytes encrypted_account_key = 5;
}
message DeleteDeviceRequest {
    plib.pUUID user_id = 1;
    plib.pUUID device_id = 2;
}
message DeleteDeviceResponse {}

// relationship management (TABLE: relationships)
// duplicate table: each relationship will ahve 2 entries
service UserRelationshipService {
    rpc CreateRelationship (CreateRelationshipRequest) returns (RelationshipObject);

    // users may have multiple relationships (e.g. they both blocked eachother)
    rpc ReadRelationship (ReadRelationshipRequest) returns (ReadRelationshipResponse);
    rpc DeleteRelationship (CreateRelationshipRequest) returns (DeleteRelationshipResponse);
    // test a specific relationship type
    rpc TestRelationship (RelationshipObject) returns (RelationshipTestResponse);

    // read all of a users relationships with others
    rpc ReadRelationships (ReadRelationshipsRequest) returns (RelationshipsResponse);

}

message CreateRelationshipRequest {
    dataservices.plib.pUUID user_id_a = 1;
    dataservices.plib.pUUID user_id_b = 2;
    int32 a_to_b_type = 3;
    int32 b_to_a_type = 4;
}

message ReadRelationshipRequest {
    dataservices.plib.pUUID user_id_a = 1;
    dataservices.plib.pUUID user_id_b = 2;
}

message RelationshipObject {
    dataservices.plib.pUUID user_id_a = 1;
    dataservices.plib.pUUID user_id_b = 2;
    int32 relationship_type = 3;
}

message ReadRelationshipResponse {
    repeated RelationshipObject relationships = 1;
}

message RelationshipTestResponse {
    bool exists = 1;
}

message ReadRelationshipsRequest {
    dataservices.plib.pUUID user_id = 1;
}

message HalfRelationship {
    dataservices.plib.pUUID user_id_b = 1;
    int32 relationship_type = 2;
}

message RelationshipsResponse {
    repeated HalfRelationship relationships = 1;
}

message DeleteRelationshipResponse {}