# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import channel_pb2 as channel__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in channel_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChannelServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateChannel = channel.unary_unary(
                '/dataservices.channelproto.ChannelService/CreateChannel',
                request_serializer=channel__pb2.CreateChannelRequest.SerializeToString,
                response_deserializer=channel__pb2.ChannelObjectResponse.FromString,
                _registered_method=True)
        self.ReadChannel = channel.unary_unary(
                '/dataservices.channelproto.ChannelService/ReadChannel',
                request_serializer=channel__pb2.ReadChannelRequest.SerializeToString,
                response_deserializer=channel__pb2.ChannelObjectResponse.FromString,
                _registered_method=True)
        self.UpdateChannel = channel.unary_unary(
                '/dataservices.channelproto.ChannelService/UpdateChannel',
                request_serializer=channel__pb2.UpdateChannelRequest.SerializeToString,
                response_deserializer=channel__pb2.ChannelObjectResponse.FromString,
                _registered_method=True)
        self.DeleteChannel = channel.unary_unary(
                '/dataservices.channelproto.ChannelService/DeleteChannel',
                request_serializer=channel__pb2.ReadChannelRequest.SerializeToString,
                response_deserializer=channel__pb2.DeleteChannelResponse.FromString,
                _registered_method=True)
        self.AddChannelMembers = channel.unary_unary(
                '/dataservices.channelproto.ChannelService/AddChannelMembers',
                request_serializer=channel__pb2.AddChannelMembersRequest.SerializeToString,
                response_deserializer=channel__pb2.AddChannelMembersResponse.FromString,
                _registered_method=True)
        self.RemoveChannelMembers = channel.unary_unary(
                '/dataservices.channelproto.ChannelService/RemoveChannelMembers',
                request_serializer=channel__pb2.RemoveChannelMembersRequest.SerializeToString,
                response_deserializer=channel__pb2.RemoveChannelMembersResponse.FromString,
                _registered_method=True)
        self.UpdateChannelMember = channel.unary_unary(
                '/dataservices.channelproto.ChannelService/UpdateChannelMember',
                request_serializer=channel__pb2.UpdateChannelMemberRequest.SerializeToString,
                response_deserializer=channel__pb2.UpdateChannelMemberResponse.FromString,
                _registered_method=True)
        self.GetUserChannels = channel.unary_unary(
                '/dataservices.channelproto.ChannelService/GetUserChannels',
                request_serializer=channel__pb2.GetUserChannelsRequest.SerializeToString,
                response_deserializer=channel__pb2.UserChannelsResponse.FromString,
                _registered_method=True)
        self.GetChannelsCounter = channel.unary_unary(
                '/dataservices.channelproto.ChannelService/GetChannelsCounter',
                request_serializer=channel__pb2.GetChannelsCounterRequest.SerializeToString,
                response_deserializer=channel__pb2.GetChannelsCounterResponse.FromString,
                _registered_method=True)
        self.IncrementChannelCounter = channel.unary_unary(
                '/dataservices.channelproto.ChannelService/IncrementChannelCounter',
                request_serializer=channel__pb2.IncrementChannelCounterRequest.SerializeToString,
                response_deserializer=channel__pb2.IncrementChannelCounterResponse.FromString,
                _registered_method=True)


class ChannelServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateChannel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadChannel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateChannel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteChannel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddChannelMembers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveChannelMembers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateChannelMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserChannels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChannelsCounter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IncrementChannelCounter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChannelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateChannel,
                    request_deserializer=channel__pb2.CreateChannelRequest.FromString,
                    response_serializer=channel__pb2.ChannelObjectResponse.SerializeToString,
            ),
            'ReadChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadChannel,
                    request_deserializer=channel__pb2.ReadChannelRequest.FromString,
                    response_serializer=channel__pb2.ChannelObjectResponse.SerializeToString,
            ),
            'UpdateChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateChannel,
                    request_deserializer=channel__pb2.UpdateChannelRequest.FromString,
                    response_serializer=channel__pb2.ChannelObjectResponse.SerializeToString,
            ),
            'DeleteChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteChannel,
                    request_deserializer=channel__pb2.ReadChannelRequest.FromString,
                    response_serializer=channel__pb2.DeleteChannelResponse.SerializeToString,
            ),
            'AddChannelMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.AddChannelMembers,
                    request_deserializer=channel__pb2.AddChannelMembersRequest.FromString,
                    response_serializer=channel__pb2.AddChannelMembersResponse.SerializeToString,
            ),
            'RemoveChannelMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveChannelMembers,
                    request_deserializer=channel__pb2.RemoveChannelMembersRequest.FromString,
                    response_serializer=channel__pb2.RemoveChannelMembersResponse.SerializeToString,
            ),
            'UpdateChannelMember': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateChannelMember,
                    request_deserializer=channel__pb2.UpdateChannelMemberRequest.FromString,
                    response_serializer=channel__pb2.UpdateChannelMemberResponse.SerializeToString,
            ),
            'GetUserChannels': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserChannels,
                    request_deserializer=channel__pb2.GetUserChannelsRequest.FromString,
                    response_serializer=channel__pb2.UserChannelsResponse.SerializeToString,
            ),
            'GetChannelsCounter': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChannelsCounter,
                    request_deserializer=channel__pb2.GetChannelsCounterRequest.FromString,
                    response_serializer=channel__pb2.GetChannelsCounterResponse.SerializeToString,
            ),
            'IncrementChannelCounter': grpc.unary_unary_rpc_method_handler(
                    servicer.IncrementChannelCounter,
                    request_deserializer=channel__pb2.IncrementChannelCounterRequest.FromString,
                    response_serializer=channel__pb2.IncrementChannelCounterResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dataservices.channelproto.ChannelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dataservices.channelproto.ChannelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChannelService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.channelproto.ChannelService/CreateChannel',
            channel__pb2.CreateChannelRequest.SerializeToString,
            channel__pb2.ChannelObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.channelproto.ChannelService/ReadChannel',
            channel__pb2.ReadChannelRequest.SerializeToString,
            channel__pb2.ChannelObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.channelproto.ChannelService/UpdateChannel',
            channel__pb2.UpdateChannelRequest.SerializeToString,
            channel__pb2.ChannelObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.channelproto.ChannelService/DeleteChannel',
            channel__pb2.ReadChannelRequest.SerializeToString,
            channel__pb2.DeleteChannelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddChannelMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.channelproto.ChannelService/AddChannelMembers',
            channel__pb2.AddChannelMembersRequest.SerializeToString,
            channel__pb2.AddChannelMembersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveChannelMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.channelproto.ChannelService/RemoveChannelMembers',
            channel__pb2.RemoveChannelMembersRequest.SerializeToString,
            channel__pb2.RemoveChannelMembersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateChannelMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.channelproto.ChannelService/UpdateChannelMember',
            channel__pb2.UpdateChannelMemberRequest.SerializeToString,
            channel__pb2.UpdateChannelMemberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserChannels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.channelproto.ChannelService/GetUserChannels',
            channel__pb2.GetUserChannelsRequest.SerializeToString,
            channel__pb2.UserChannelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChannelsCounter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.channelproto.ChannelService/GetChannelsCounter',
            channel__pb2.GetChannelsCounterRequest.SerializeToString,
            channel__pb2.GetChannelsCounterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IncrementChannelCounter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.channelproto.ChannelService/IncrementChannelCounter',
            channel__pb2.IncrementChannelCounterRequest.SerializeToString,
            channel__pb2.IncrementChannelCounterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
