# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import feed_pb2 as feed__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in feed_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FeedServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadFeedMeta = channel.unary_unary(
                '/dataservices.feedproto.FeedService/ReadFeedMeta',
                request_serializer=feed__pb2.ReadFeedMetaRequest.SerializeToString,
                response_deserializer=feed__pb2.FeedMetaResponse.FromString,
                _registered_method=True)
        self.UpdateFeedMeta = channel.unary_unary(
                '/dataservices.feedproto.FeedService/UpdateFeedMeta',
                request_serializer=feed__pb2.UpdateFeedMetaRequest.SerializeToString,
                response_deserializer=feed__pb2.FeedMetaResponse.FromString,
                _registered_method=True)
        self.ReadFeed = channel.unary_unary(
                '/dataservices.feedproto.FeedService/ReadFeed',
                request_serializer=feed__pb2.ReadFeedRequest.SerializeToString,
                response_deserializer=feed__pb2.FeedResponse.FromString,
                _registered_method=True)
        self.AddToFeeds = channel.unary_unary(
                '/dataservices.feedproto.FeedService/AddToFeeds',
                request_serializer=feed__pb2.AddToFeedsRequest.SerializeToString,
                response_deserializer=feed__pb2.AddToFeedsResponse.FromString,
                _registered_method=True)
        self.RemoveFromFeed = channel.unary_unary(
                '/dataservices.feedproto.FeedService/RemoveFromFeed',
                request_serializer=feed__pb2.RemovePostsFromFeedRequest.SerializeToString,
                response_deserializer=feed__pb2.RemovePostsFromFeedResponse.FromString,
                _registered_method=True)
        self.AddPostsToFeed = channel.unary_unary(
                '/dataservices.feedproto.FeedService/AddPostsToFeed',
                request_serializer=feed__pb2.AddPostsToFeedRequest.SerializeToString,
                response_deserializer=feed__pb2.AddPostsToFeedResponse.FromString,
                _registered_method=True)


class FeedServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReadFeedMeta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateFeedMeta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFeed(self, request, context):
        """/ Read a users feed
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddToFeeds(self, request, context):
        """/ Add a post to many feeds (fan out)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveFromFeed(self, request, context):
        """/ Remove many posts from a users feed (fan in)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddPostsToFeed(self, request, context):
        """/ Add posts to a feed (fan in)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FeedServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadFeedMeta': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadFeedMeta,
                    request_deserializer=feed__pb2.ReadFeedMetaRequest.FromString,
                    response_serializer=feed__pb2.FeedMetaResponse.SerializeToString,
            ),
            'UpdateFeedMeta': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateFeedMeta,
                    request_deserializer=feed__pb2.UpdateFeedMetaRequest.FromString,
                    response_serializer=feed__pb2.FeedMetaResponse.SerializeToString,
            ),
            'ReadFeed': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadFeed,
                    request_deserializer=feed__pb2.ReadFeedRequest.FromString,
                    response_serializer=feed__pb2.FeedResponse.SerializeToString,
            ),
            'AddToFeeds': grpc.unary_unary_rpc_method_handler(
                    servicer.AddToFeeds,
                    request_deserializer=feed__pb2.AddToFeedsRequest.FromString,
                    response_serializer=feed__pb2.AddToFeedsResponse.SerializeToString,
            ),
            'RemoveFromFeed': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveFromFeed,
                    request_deserializer=feed__pb2.RemovePostsFromFeedRequest.FromString,
                    response_serializer=feed__pb2.RemovePostsFromFeedResponse.SerializeToString,
            ),
            'AddPostsToFeed': grpc.unary_unary_rpc_method_handler(
                    servicer.AddPostsToFeed,
                    request_deserializer=feed__pb2.AddPostsToFeedRequest.FromString,
                    response_serializer=feed__pb2.AddPostsToFeedResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dataservices.feedproto.FeedService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dataservices.feedproto.FeedService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FeedService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReadFeedMeta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.feedproto.FeedService/ReadFeedMeta',
            feed__pb2.ReadFeedMetaRequest.SerializeToString,
            feed__pb2.FeedMetaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateFeedMeta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.feedproto.FeedService/UpdateFeedMeta',
            feed__pb2.UpdateFeedMetaRequest.SerializeToString,
            feed__pb2.FeedMetaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadFeed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.feedproto.FeedService/ReadFeed',
            feed__pb2.ReadFeedRequest.SerializeToString,
            feed__pb2.FeedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddToFeeds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.feedproto.FeedService/AddToFeeds',
            feed__pb2.AddToFeedsRequest.SerializeToString,
            feed__pb2.AddToFeedsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveFromFeed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.feedproto.FeedService/RemoveFromFeed',
            feed__pb2.RemovePostsFromFeedRequest.SerializeToString,
            feed__pb2.RemovePostsFromFeedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddPostsToFeed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.feedproto.FeedService/AddPostsToFeed',
            feed__pb2.AddPostsToFeedRequest.SerializeToString,
            feed__pb2.AddPostsToFeedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
