# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import plib_pb2 as plib__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08gc.proto\x12\x14\x64\x61taservices.gcproto\x1a\nplib.proto\"q\n\x12\x46ileGarbageRequest\x12\x0e\n\x06\x62ucket\x18\x01 \x01(\x03\x12\x1e\n\tobject_id\x18\x02 \x01(\x0b\x32\x0b.plib.pUUID\x12\x14\n\x0cgarbage_type\x18\x03 \x01(\x05\x12\x15\n\rgarbage_flags\x18\x04 \x01(\x04\"\x15\n\x13\x46ileGarbageResponse\"O\n\x12ReadGarbageRequest\x12\x0e\n\x06\x62ucket\x18\x01 \x01(\x03\x12\x1a\n\x05\x61\x66ter\x18\x02 \x01(\x0b\x32\x0b.plib.pUUID\x12\r\n\x05limit\x18\x03 \x01(\x05\"L\n\x0fGarbageResponse\x12\x39\n\x0e\x66or_collection\x18\x01 \x03(\x0b\x32!.dataservices.gcproto.GarbageItem\"j\n\x0bGarbageItem\x12\x0e\n\x06\x62ucket\x18\x01 \x01(\x03\x12\x1e\n\tobject_id\x18\x02 \x01(\x0b\x32\x0b.plib.pUUID\x12\x14\n\x0cgarbage_type\x18\x03 \x01(\x05\x12\x15\n\rgarbage_flags\x18\x04 \x01(\x04\"F\n\x14\x44\x65leteGarbageRequest\x12\x0e\n\x06\x62ucket\x18\x01 \x01(\x03\x12\x1e\n\tobject_id\x18\x02 \x01(\x0b\x32\x0b.plib.pUUID\"\x17\n\x15\x44\x65leteGarbageResponse2\xc4\x02\n\x0eGarbageService\x12h\n\x11\x46ileForCollection\x12(.dataservices.gcproto.FileGarbageRequest\x1a).dataservices.gcproto.FileGarbageResponse\x12^\n\x0bReadGarbage\x12(.dataservices.gcproto.ReadGarbageRequest\x1a%.dataservices.gcproto.GarbageResponse\x12h\n\rDeleteGarbage\x12*.dataservices.gcproto.DeleteGarbageRequest\x1a+.dataservices.gcproto.DeleteGarbageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILEGARBAGEREQUEST']._serialized_start=46
  _globals['_FILEGARBAGEREQUEST']._serialized_end=159
  _globals['_FILEGARBAGERESPONSE']._serialized_start=161
  _globals['_FILEGARBAGERESPONSE']._serialized_end=182
  _globals['_READGARBAGEREQUEST']._serialized_start=184
  _globals['_READGARBAGEREQUEST']._serialized_end=263
  _globals['_GARBAGERESPONSE']._serialized_start=265
  _globals['_GARBAGERESPONSE']._serialized_end=341
  _globals['_GARBAGEITEM']._serialized_start=343
  _globals['_GARBAGEITEM']._serialized_end=449
  _globals['_DELETEGARBAGEREQUEST']._serialized_start=451
  _globals['_DELETEGARBAGEREQUEST']._serialized_end=521
  _globals['_DELETEGARBAGERESPONSE']._serialized_start=523
  _globals['_DELETEGARBAGERESPONSE']._serialized_end=546
  _globals['_GARBAGESERVICE']._serialized_start=549
  _globals['_GARBAGESERVICE']._serialized_end=873
# @@protoc_insertion_point(module_scope)
