# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import gc_pb2 as gc__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GarbageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FileForCollection = channel.unary_unary(
                '/dataservices.gcproto.GarbageService/FileForCollection',
                request_serializer=gc__pb2.FileGarbageRequest.SerializeToString,
                response_deserializer=gc__pb2.FileGarbageResponse.FromString,
                _registered_method=True)
        self.ReadGarbage = channel.unary_unary(
                '/dataservices.gcproto.GarbageService/ReadGarbage',
                request_serializer=gc__pb2.ReadGarbageRequest.SerializeToString,
                response_deserializer=gc__pb2.GarbageResponse.FromString,
                _registered_method=True)
        self.DeleteGarbage = channel.unary_unary(
                '/dataservices.gcproto.GarbageService/DeleteGarbage',
                request_serializer=gc__pb2.DeleteGarbageRequest.SerializeToString,
                response_deserializer=gc__pb2.DeleteGarbageResponse.FromString,
                _registered_method=True)


class GarbageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FileForCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadGarbage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteGarbage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GarbageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FileForCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.FileForCollection,
                    request_deserializer=gc__pb2.FileGarbageRequest.FromString,
                    response_serializer=gc__pb2.FileGarbageResponse.SerializeToString,
            ),
            'ReadGarbage': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadGarbage,
                    request_deserializer=gc__pb2.ReadGarbageRequest.FromString,
                    response_serializer=gc__pb2.GarbageResponse.SerializeToString,
            ),
            'DeleteGarbage': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteGarbage,
                    request_deserializer=gc__pb2.DeleteGarbageRequest.FromString,
                    response_serializer=gc__pb2.DeleteGarbageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dataservices.gcproto.GarbageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dataservices.gcproto.GarbageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GarbageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FileForCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.gcproto.GarbageService/FileForCollection',
            gc__pb2.FileGarbageRequest.SerializeToString,
            gc__pb2.FileGarbageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadGarbage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.gcproto.GarbageService/ReadGarbage',
            gc__pb2.ReadGarbageRequest.SerializeToString,
            gc__pb2.GarbageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteGarbage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.gcproto.GarbageService/DeleteGarbage',
            gc__pb2.DeleteGarbageRequest.SerializeToString,
            gc__pb2.DeleteGarbageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
