# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import media_pb2 as media__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in media_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TransformerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TransformImage = channel.unary_unary(
                '/mediaservices.transformer.TransformerService/TransformImage',
                request_serializer=media__pb2.TransformImageRequest.SerializeToString,
                response_deserializer=media__pb2.TransformImageResponse.FromString,
                _registered_method=True)
        self.TransformVideo = channel.stream_unary(
                '/mediaservices.transformer.TransformerService/TransformVideo',
                request_serializer=media__pb2.MediaInput.SerializeToString,
                response_deserializer=media__pb2.TransformVideoResponse.FromString,
                _registered_method=True)


class TransformerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TransformImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransformVideo(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransformerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TransformImage': grpc.unary_unary_rpc_method_handler(
                    servicer.TransformImage,
                    request_deserializer=media__pb2.TransformImageRequest.FromString,
                    response_serializer=media__pb2.TransformImageResponse.SerializeToString,
            ),
            'TransformVideo': grpc.stream_unary_rpc_method_handler(
                    servicer.TransformVideo,
                    request_deserializer=media__pb2.MediaInput.FromString,
                    response_serializer=media__pb2.TransformVideoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mediaservices.transformer.TransformerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mediaservices.transformer.TransformerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TransformerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TransformImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mediaservices.transformer.TransformerService/TransformImage',
            media__pb2.TransformImageRequest.SerializeToString,
            media__pb2.TransformImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransformVideo(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/mediaservices.transformer.TransformerService/TransformVideo',
            media__pb2.MediaInput.SerializeToString,
            media__pb2.TransformVideoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
