# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import message_pb2 as message__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in message_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MessageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateMessage = channel.unary_unary(
                '/dataservices.messageproto.MessageService/CreateMessage',
                request_serializer=message__pb2.CreateMessageRequest.SerializeToString,
                response_deserializer=message__pb2.MessageObject.FromString,
                _registered_method=True)
        self.UpdateMessage = channel.unary_unary(
                '/dataservices.messageproto.MessageService/UpdateMessage',
                request_serializer=message__pb2.UpdateMessageRequest.SerializeToString,
                response_deserializer=message__pb2.MessageObject.FromString,
                _registered_method=True)
        self.ReadMessage = channel.unary_unary(
                '/dataservices.messageproto.MessageService/ReadMessage',
                request_serializer=message__pb2.ReadMessageRequest.SerializeToString,
                response_deserializer=message__pb2.MessageObject.FromString,
                _registered_method=True)
        self.DeleteMessage = channel.unary_unary(
                '/dataservices.messageproto.MessageService/DeleteMessage',
                request_serializer=message__pb2.DeleteMessageRequest.SerializeToString,
                response_deserializer=message__pb2.DeleteMessageResponse.FromString,
                _registered_method=True)
        self.DeleteMessagesByBucket = channel.unary_unary(
                '/dataservices.messageproto.MessageService/DeleteMessagesByBucket',
                request_serializer=message__pb2.DeleteMessagesByBucketRequest.SerializeToString,
                response_deserializer=message__pb2.DeleteMessagesByBucketResponse.FromString,
                _registered_method=True)
        self.ReadMessages = channel.unary_unary(
                '/dataservices.messageproto.MessageService/ReadMessages',
                request_serializer=message__pb2.ReadMessagesRequest.SerializeToString,
                response_deserializer=message__pb2.ReadMessagesResponse.FromString,
                _registered_method=True)


class MessageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMessagesByBucket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMessage,
                    request_deserializer=message__pb2.CreateMessageRequest.FromString,
                    response_serializer=message__pb2.MessageObject.SerializeToString,
            ),
            'UpdateMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMessage,
                    request_deserializer=message__pb2.UpdateMessageRequest.FromString,
                    response_serializer=message__pb2.MessageObject.SerializeToString,
            ),
            'ReadMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadMessage,
                    request_deserializer=message__pb2.ReadMessageRequest.FromString,
                    response_serializer=message__pb2.MessageObject.SerializeToString,
            ),
            'DeleteMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMessage,
                    request_deserializer=message__pb2.DeleteMessageRequest.FromString,
                    response_serializer=message__pb2.DeleteMessageResponse.SerializeToString,
            ),
            'DeleteMessagesByBucket': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMessagesByBucket,
                    request_deserializer=message__pb2.DeleteMessagesByBucketRequest.FromString,
                    response_serializer=message__pb2.DeleteMessagesByBucketResponse.SerializeToString,
            ),
            'ReadMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadMessages,
                    request_deserializer=message__pb2.ReadMessagesRequest.FromString,
                    response_serializer=message__pb2.ReadMessagesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dataservices.messageproto.MessageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dataservices.messageproto.MessageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MessageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.messageproto.MessageService/CreateMessage',
            message__pb2.CreateMessageRequest.SerializeToString,
            message__pb2.MessageObject.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.messageproto.MessageService/UpdateMessage',
            message__pb2.UpdateMessageRequest.SerializeToString,
            message__pb2.MessageObject.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.messageproto.MessageService/ReadMessage',
            message__pb2.ReadMessageRequest.SerializeToString,
            message__pb2.MessageObject.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.messageproto.MessageService/DeleteMessage',
            message__pb2.DeleteMessageRequest.SerializeToString,
            message__pb2.DeleteMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMessagesByBucket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.messageproto.MessageService/DeleteMessagesByBucket',
            message__pb2.DeleteMessagesByBucketRequest.SerializeToString,
            message__pb2.DeleteMessagesByBucketResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.messageproto.MessageService/ReadMessages',
            message__pb2.ReadMessagesRequest.SerializeToString,
            message__pb2.ReadMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
