# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import user_pb2 as user__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in user_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServiceStub(object):
    """User Management (TABLE: account)

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateUser = channel.unary_unary(
                '/dataservices.userproto.UserService/CreateUser',
                request_serializer=user__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=user__pb2.ReadUserResponse.FromString,
                _registered_method=True)
        self.UpdateUser = channel.unary_unary(
                '/dataservices.userproto.UserService/UpdateUser',
                request_serializer=user__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=user__pb2.ReadUserResponse.FromString,
                _registered_method=True)
        self.ReadUser = channel.unary_unary(
                '/dataservices.userproto.UserService/ReadUser',
                request_serializer=user__pb2.ReadUserRequest.SerializeToString,
                response_deserializer=user__pb2.ReadUserResponse.FromString,
                _registered_method=True)
        self.ReadUserByUsername = channel.unary_unary(
                '/dataservices.userproto.UserService/ReadUserByUsername',
                request_serializer=user__pb2.ReadUserByUsernameRequest.SerializeToString,
                response_deserializer=user__pb2.ReadUserResponse.FromString,
                _registered_method=True)
        self.DeleteUser = channel.unary_unary(
                '/dataservices.userproto.UserService/DeleteUser',
                request_serializer=user__pb2.DeleteUserRequest.SerializeToString,
                response_deserializer=user__pb2.DeleteUserResponse.FromString,
                _registered_method=True)
        self.CheckUsername = channel.unary_unary(
                '/dataservices.userproto.UserService/CheckUsername',
                request_serializer=user__pb2.ReadUserByUsernameRequest.SerializeToString,
                response_deserializer=user__pb2.CheckUsernameResponse.FromString,
                _registered_method=True)
        self.UserBulkReader = channel.unary_unary(
                '/dataservices.userproto.UserService/UserBulkReader',
                request_serializer=user__pb2.ReadUserBulkRequest.SerializeToString,
                response_deserializer=user__pb2.BulkUserResponse.FromString,
                _registered_method=True)
        self.UsernameSearcher = channel.unary_unary(
                '/dataservices.userproto.UserService/UsernameSearcher',
                request_serializer=user__pb2.UsernameSearch.SerializeToString,
                response_deserializer=user__pb2.BulkUserResponse.FromString,
                _registered_method=True)


class UserServiceServicer(object):
    """User Management (TABLE: account)

    """

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadUserByUsername(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckUsername(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UserBulkReader(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UsernameSearcher(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=user__pb2.CreateUserRequest.FromString,
                    response_serializer=user__pb2.ReadUserResponse.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=user__pb2.UpdateUserRequest.FromString,
                    response_serializer=user__pb2.ReadUserResponse.SerializeToString,
            ),
            'ReadUser': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadUser,
                    request_deserializer=user__pb2.ReadUserRequest.FromString,
                    response_serializer=user__pb2.ReadUserResponse.SerializeToString,
            ),
            'ReadUserByUsername': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadUserByUsername,
                    request_deserializer=user__pb2.ReadUserByUsernameRequest.FromString,
                    response_serializer=user__pb2.ReadUserResponse.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=user__pb2.DeleteUserRequest.FromString,
                    response_serializer=user__pb2.DeleteUserResponse.SerializeToString,
            ),
            'CheckUsername': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckUsername,
                    request_deserializer=user__pb2.ReadUserByUsernameRequest.FromString,
                    response_serializer=user__pb2.CheckUsernameResponse.SerializeToString,
            ),
            'UserBulkReader': grpc.unary_unary_rpc_method_handler(
                    servicer.UserBulkReader,
                    request_deserializer=user__pb2.ReadUserBulkRequest.FromString,
                    response_serializer=user__pb2.BulkUserResponse.SerializeToString,
            ),
            'UsernameSearcher': grpc.unary_unary_rpc_method_handler(
                    servicer.UsernameSearcher,
                    request_deserializer=user__pb2.UsernameSearch.FromString,
                    response_serializer=user__pb2.BulkUserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dataservices.userproto.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dataservices.userproto.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """User Management (TABLE: account)

    """

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.userproto.UserService/CreateUser',
            user__pb2.CreateUserRequest.SerializeToString,
            user__pb2.ReadUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.userproto.UserService/UpdateUser',
            user__pb2.UpdateUserRequest.SerializeToString,
            user__pb2.ReadUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.userproto.UserService/ReadUser',
            user__pb2.ReadUserRequest.SerializeToString,
            user__pb2.ReadUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadUserByUsername(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.userproto.UserService/ReadUserByUsername',
            user__pb2.ReadUserByUsernameRequest.SerializeToString,
            user__pb2.ReadUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.userproto.UserService/DeleteUser',
            user__pb2.DeleteUserRequest.SerializeToString,
            user__pb2.DeleteUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckUsername(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.userproto.UserService/CheckUsername',
            user__pb2.ReadUserByUsernameRequest.SerializeToString,
            user__pb2.CheckUsernameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UserBulkReader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.userproto.UserService/UserBulkReader',
            user__pb2.ReadUserBulkRequest.SerializeToString,
            user__pb2.BulkUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UsernameSearcher(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.userproto.UserService/UsernameSearcher',
            user__pb2.UsernameSearch.SerializeToString,
            user__pb2.BulkUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class UserDeviceServiceStub(object):
    """User Device Management (TABLE: user_device)

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateDevice = channel.unary_unary(
                '/dataservices.userproto.UserDeviceService/CreateDevice',
                request_serializer=user__pb2.CreateDeviceRequest.SerializeToString,
                response_deserializer=user__pb2.DeviceObjectResponse.FromString,
                _registered_method=True)
        self.ReadDevices = channel.unary_unary(
                '/dataservices.userproto.UserDeviceService/ReadDevices',
                request_serializer=user__pb2.ReadDevicesRequest.SerializeToString,
                response_deserializer=user__pb2.ReadDevicesResponse.FromString,
                _registered_method=True)
        self.ReadDevice = channel.unary_unary(
                '/dataservices.userproto.UserDeviceService/ReadDevice',
                request_serializer=user__pb2.ReadDeviceRequest.SerializeToString,
                response_deserializer=user__pb2.DeviceObjectResponse.FromString,
                _registered_method=True)
        self.UpdateDevice = channel.unary_unary(
                '/dataservices.userproto.UserDeviceService/UpdateDevice',
                request_serializer=user__pb2.UpdateDeviceRequest.SerializeToString,
                response_deserializer=user__pb2.DeviceObjectResponse.FromString,
                _registered_method=True)
        self.DeleteDevice = channel.unary_unary(
                '/dataservices.userproto.UserDeviceService/DeleteDevice',
                request_serializer=user__pb2.DeleteDeviceRequest.SerializeToString,
                response_deserializer=user__pb2.DeleteDeviceResponse.FromString,
                _registered_method=True)


class UserDeviceServiceServicer(object):
    """User Device Management (TABLE: user_device)

    """

    def CreateDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadDevices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserDeviceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDevice,
                    request_deserializer=user__pb2.CreateDeviceRequest.FromString,
                    response_serializer=user__pb2.DeviceObjectResponse.SerializeToString,
            ),
            'ReadDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadDevices,
                    request_deserializer=user__pb2.ReadDevicesRequest.FromString,
                    response_serializer=user__pb2.ReadDevicesResponse.SerializeToString,
            ),
            'ReadDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadDevice,
                    request_deserializer=user__pb2.ReadDeviceRequest.FromString,
                    response_serializer=user__pb2.DeviceObjectResponse.SerializeToString,
            ),
            'UpdateDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDevice,
                    request_deserializer=user__pb2.UpdateDeviceRequest.FromString,
                    response_serializer=user__pb2.DeviceObjectResponse.SerializeToString,
            ),
            'DeleteDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDevice,
                    request_deserializer=user__pb2.DeleteDeviceRequest.FromString,
                    response_serializer=user__pb2.DeleteDeviceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dataservices.userproto.UserDeviceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dataservices.userproto.UserDeviceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserDeviceService(object):
    """User Device Management (TABLE: user_device)

    """

    @staticmethod
    def CreateDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.userproto.UserDeviceService/CreateDevice',
            user__pb2.CreateDeviceRequest.SerializeToString,
            user__pb2.DeviceObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.userproto.UserDeviceService/ReadDevices',
            user__pb2.ReadDevicesRequest.SerializeToString,
            user__pb2.ReadDevicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.userproto.UserDeviceService/ReadDevice',
            user__pb2.ReadDeviceRequest.SerializeToString,
            user__pb2.DeviceObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.userproto.UserDeviceService/UpdateDevice',
            user__pb2.UpdateDeviceRequest.SerializeToString,
            user__pb2.DeviceObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.userproto.UserDeviceService/DeleteDevice',
            user__pb2.DeleteDeviceRequest.SerializeToString,
            user__pb2.DeleteDeviceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class UserRelationshipServiceStub(object):
    """relationship management (TABLE: relationships)
    duplicate table: each relationship will ahve 2 entries
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateRelationship = channel.unary_unary(
                '/dataservices.userproto.UserRelationshipService/CreateRelationship',
                request_serializer=user__pb2.CreateRelationshipRequest.SerializeToString,
                response_deserializer=user__pb2.RelationshipObject.FromString,
                _registered_method=True)
        self.ReadRelationship = channel.unary_unary(
                '/dataservices.userproto.UserRelationshipService/ReadRelationship',
                request_serializer=user__pb2.ReadRelationshipRequest.SerializeToString,
                response_deserializer=user__pb2.ReadRelationshipResponse.FromString,
                _registered_method=True)
        self.DeleteRelationship = channel.unary_unary(
                '/dataservices.userproto.UserRelationshipService/DeleteRelationship',
                request_serializer=user__pb2.CreateRelationshipRequest.SerializeToString,
                response_deserializer=user__pb2.DeleteRelationshipResponse.FromString,
                _registered_method=True)
        self.TestRelationship = channel.unary_unary(
                '/dataservices.userproto.UserRelationshipService/TestRelationship',
                request_serializer=user__pb2.RelationshipObject.SerializeToString,
                response_deserializer=user__pb2.RelationshipTestResponse.FromString,
                _registered_method=True)
        self.TestManyRelationships = channel.unary_unary(
                '/dataservices.userproto.UserRelationshipService/TestManyRelationships',
                request_serializer=user__pb2.TestManyRelationshipsRequest.SerializeToString,
                response_deserializer=user__pb2.TestManyRelationshipsResponse.FromString,
                _registered_method=True)
        self.ReadRelationships = channel.unary_unary(
                '/dataservices.userproto.UserRelationshipService/ReadRelationships',
                request_serializer=user__pb2.ReadRelationshipsRequest.SerializeToString,
                response_deserializer=user__pb2.RelationshipsResponse.FromString,
                _registered_method=True)
        self.ReadRelationshipsChunked = channel.unary_unary(
                '/dataservices.userproto.UserRelationshipService/ReadRelationshipsChunked',
                request_serializer=user__pb2.ReadRelationshipsChunkedRequest.SerializeToString,
                response_deserializer=user__pb2.RelationshipsResponse.FromString,
                _registered_method=True)
        self.GetUserRelationshipCounts = channel.unary_unary(
                '/dataservices.userproto.UserRelationshipService/GetUserRelationshipCounts',
                request_serializer=user__pb2.GetUserRelationshipCountsRequest.SerializeToString,
                response_deserializer=user__pb2.GetUserRelationshipCountsResponse.FromString,
                _registered_method=True)


class UserRelationshipServiceServicer(object):
    """relationship management (TABLE: relationships)
    duplicate table: each relationship will ahve 2 entries
    """

    def CreateRelationship(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadRelationship(self, request, context):
        """users may have multiple relationships (e.g. they both blocked eachother)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRelationship(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestRelationship(self, request, context):
        """test a specific relationship type
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestManyRelationships(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadRelationships(self, request, context):
        """read all of a users relationships with others
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadRelationshipsChunked(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserRelationshipCounts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserRelationshipServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateRelationship': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRelationship,
                    request_deserializer=user__pb2.CreateRelationshipRequest.FromString,
                    response_serializer=user__pb2.RelationshipObject.SerializeToString,
            ),
            'ReadRelationship': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadRelationship,
                    request_deserializer=user__pb2.ReadRelationshipRequest.FromString,
                    response_serializer=user__pb2.ReadRelationshipResponse.SerializeToString,
            ),
            'DeleteRelationship': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRelationship,
                    request_deserializer=user__pb2.CreateRelationshipRequest.FromString,
                    response_serializer=user__pb2.DeleteRelationshipResponse.SerializeToString,
            ),
            'TestRelationship': grpc.unary_unary_rpc_method_handler(
                    servicer.TestRelationship,
                    request_deserializer=user__pb2.RelationshipObject.FromString,
                    response_serializer=user__pb2.RelationshipTestResponse.SerializeToString,
            ),
            'TestManyRelationships': grpc.unary_unary_rpc_method_handler(
                    servicer.TestManyRelationships,
                    request_deserializer=user__pb2.TestManyRelationshipsRequest.FromString,
                    response_serializer=user__pb2.TestManyRelationshipsResponse.SerializeToString,
            ),
            'ReadRelationships': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadRelationships,
                    request_deserializer=user__pb2.ReadRelationshipsRequest.FromString,
                    response_serializer=user__pb2.RelationshipsResponse.SerializeToString,
            ),
            'ReadRelationshipsChunked': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadRelationshipsChunked,
                    request_deserializer=user__pb2.ReadRelationshipsChunkedRequest.FromString,
                    response_serializer=user__pb2.RelationshipsResponse.SerializeToString,
            ),
            'GetUserRelationshipCounts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserRelationshipCounts,
                    request_deserializer=user__pb2.GetUserRelationshipCountsRequest.FromString,
                    response_serializer=user__pb2.GetUserRelationshipCountsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dataservices.userproto.UserRelationshipService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dataservices.userproto.UserRelationshipService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserRelationshipService(object):
    """relationship management (TABLE: relationships)
    duplicate table: each relationship will ahve 2 entries
    """

    @staticmethod
    def CreateRelationship(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.userproto.UserRelationshipService/CreateRelationship',
            user__pb2.CreateRelationshipRequest.SerializeToString,
            user__pb2.RelationshipObject.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadRelationship(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.userproto.UserRelationshipService/ReadRelationship',
            user__pb2.ReadRelationshipRequest.SerializeToString,
            user__pb2.ReadRelationshipResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRelationship(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.userproto.UserRelationshipService/DeleteRelationship',
            user__pb2.CreateRelationshipRequest.SerializeToString,
            user__pb2.DeleteRelationshipResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TestRelationship(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.userproto.UserRelationshipService/TestRelationship',
            user__pb2.RelationshipObject.SerializeToString,
            user__pb2.RelationshipTestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TestManyRelationships(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.userproto.UserRelationshipService/TestManyRelationships',
            user__pb2.TestManyRelationshipsRequest.SerializeToString,
            user__pb2.TestManyRelationshipsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadRelationships(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.userproto.UserRelationshipService/ReadRelationships',
            user__pb2.ReadRelationshipsRequest.SerializeToString,
            user__pb2.RelationshipsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadRelationshipsChunked(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.userproto.UserRelationshipService/ReadRelationshipsChunked',
            user__pb2.ReadRelationshipsChunkedRequest.SerializeToString,
            user__pb2.RelationshipsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserRelationshipCounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataservices.userproto.UserRelationshipService/GetUserRelationshipCounts',
            user__pb2.GetUserRelationshipCountsRequest.SerializeToString,
            user__pb2.GetUserRelationshipCountsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
