name: 'rsync UI to gcp bucket'

on:
  push:
    branches:
      - 'main'

jobs:
    'deploy-ui':
      runs-on: 'ubuntu-latest'
      permissions:
        contents: 'read'
        id-token: 'write'

      steps:
        - id: 'checkout'
          uses: 'actions/checkout@v4'
    
        - id: 'auth'
          uses: 'google-github-actions/auth@v1'
          with:
            credentials_json: '${{secrets.GCP_UI_DEPLOY_ACCOUNT}}'

        - name: 'Set up Cloud SDK'
          uses: 'google-github-actions/setup-gcloud@v2'
      
        - name: 'gsutil rsync to gcp bucket'
          run: 'gsutil -m -h "Cache-Control:no-cache" rsync -R -d ui gs://az7.chat/'